// src/app/admin/statistics/page.tsx
'use client';

import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { parseAsString, useQueryStates } from 'nuqs';
import {
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts';
import { formatCurrency, statusLabel } from '@/lib/utils/format';
import { currentYearInTz } from '@/lib/date';
import { ORDER_STATUS_OPTIONS } from '@/lib/constants/order';
import { Button } from '@/components/ui/button';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';

type StatisticsResponse = {
  revenue: {
    monthly: Array<{ month: number; total: number; count: number }>;
    total: number;
  };
  ordersByArea: {
    byDistrict: Array<{ district: string; count: number; total: number }>;
    byWard: Array<{
      district: string;
      ward: string;
      count: number;
      total: number;
    }>;
  };
  summary: {
    totalOrders: number;
    totalRevenue: number;
    avgOrderValue: number;
  };
};

const MONTH_OPTIONS = [{ label: 'Cả năm', value: '' }].concat(
  Array.from({ length: 12 }, (_, index) => ({
    label: `Tháng ${index + 1}`,
    value: String(index + 1),
  })),
);

const STATUS_OPTIONS = [
  { label: 'Tất cả trạng thái', value: '' },
  ...ORDER_STATUS_OPTIONS,
];

export default function AdminStatisticsPage() {
  const currentYear = currentYearInTz();
  const yearOptions = useMemo(
    () => Array.from({ length: 6 }, (_, index) => String(currentYear - index)),
    [currentYear],
  );
  const [areaTab, setAreaTab] = useState<'district' | 'ward'>('district');
  const [f, setF] = useQueryStates({
    y: parseAsString.withDefault(String(currentYear)),
    m: parseAsString.withDefault(''),
    s: parseAsString.withDefault(''),
  });

  const statisticsQuery = useQuery({
    queryKey: [
      'admin',
      'statistics',
      f.y,
      f.m,
      f.s,
    ],
    queryFn: async () => {
      const params = new URLSearchParams();
      if (f.y) params.set('year', f.y);
      if (f.m) params.set('month', f.m);
      if (f.s) params.set('status', f.s);
      const response = await fetch(
        `/api/admin/statistics?${params.toString()}`,
      );
      const payload = (await response.json()) as StatisticsResponse;
      if (!response.ok)
        throw new Error(
          (payload as { message?: string }).message ??
            'Không tải được thống kê',
        );
      return payload;
    },
  });

  const stats = statisticsQuery.data ?? {
    revenue: { monthly: [], total: 0 },
    ordersByArea: { byDistrict: [], byWard: [] },
    summary: { totalOrders: 0, totalRevenue: 0, avgOrderValue: 0 },
  };

  const revenueChartData = stats.revenue.monthly.map((row) => ({
    month: `T${row.month}`,
    revenue: row.total,
    orders: row.count,
  }));

  const areaRows =
    areaTab === 'district'
      ? stats.ordersByArea.byDistrict.map((row) => ({
          label: row.district,
          count: row.count,
          total: row.total,
        }))
      : stats.ordersByArea.byWard.map((row) => ({
          label: `${row.ward} (${row.district})`,
          count: row.count,
          total: row.total,
        }));

  return (
    <div className="container-shell space-y-5">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="text-3xl font-bold">Thống kê</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Doanh thu, số lượng đơn và phân bổ theo khu vực.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <Select
            value={f.y}
            onValueChange={(value) => setF({ y: value })}
          >
            <SelectTrigger className="w-[140px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {yearOptions.map((yearOption) => (
                <SelectItem key={yearOption} value={yearOption}>
                  {yearOption}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select
            value={f.m || 'all-month'}
            onValueChange={(value) =>
              setF({ m: value === 'all-month' ? '' : value })
            }
          >
            <SelectTrigger className="w-[140px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {MONTH_OPTIONS.map((option) => (
                <SelectItem
                  key={option.value || 'all-month'}
                  value={option.value || 'all-month'}
                >
                  {option.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select
            value={f.s || 'all-status'}
            onValueChange={(value) =>
              setF({ s: value === 'all-status' ? '' : value })
            }
          >
            <SelectTrigger className="w-[220px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {STATUS_OPTIONS.map((option) => (
                <SelectItem
                  key={option.value || 'all-status'}
                  value={option.value || 'all-status'}
                >
                  {option.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>

      {statisticsQuery.isError ? (
        <div className="rounded-md border border-destructive/50 bg-destructive/10 px-4 py-3 text-sm text-foreground">
          {statisticsQuery.error.message}
        </div>
      ) : null}

      <div className="grid gap-2.5 sm:grid-cols-2 lg:grid-cols-3">
        <StatCard
          title="Tổng doanh thu"
          value={formatCurrency(stats.summary.totalRevenue)}
        />
        <StatCard
          title="Tổng số đơn"
          value={String(stats.summary.totalOrders)}
        />
        <StatCard
          title="Giá trị đơn trung bình"
          value={formatCurrency(stats.summary.avgOrderValue)}
        />
      </div>

      <section className="rounded-md border border-border bg-card p-4">
        <h2 className="text-xl font-semibold">Doanh thu theo tháng</h2>
        {statisticsQuery.isPending ? (
          <p className="mt-3 text-sm text-muted-foreground">
            Đang tải dữ liệu...
          </p>
        ) : revenueChartData.length === 0 ? (
          <p className="mt-3 text-sm text-muted-foreground">
            Không có dữ liệu.
          </p>
        ) : (
          <div className="mt-3 h-[320px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={revenueChartData}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="month" />
                <YAxis />
                <Tooltip />
                <Legend />
                <Bar
                  dataKey="revenue"
                  fill="var(--color-chart-1)"
                  name="Doanh thu"
                />
              </BarChart>
            </ResponsiveContainer>
          </div>
        )}
      </section>

      <section className="rounded-md border border-border bg-card p-4">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <h2 className="text-xl font-semibold">Số lượng theo khu vực</h2>
          <div className="inline-flex rounded-md border p-1 text-sm">
            <Button
              type="button"
              variant={areaTab === 'district' ? 'secondary' : 'ghost'}
              size="sm"
              onClick={() => setAreaTab('district')}
            >
              Quận/Huyện
            </Button>
            <Button
              type="button"
              variant={areaTab === 'ward' ? 'secondary' : 'ghost'}
              size="sm"
              onClick={() => setAreaTab('ward')}
            >
              Phường/Xã
            </Button>
          </div>
        </div>

        {statisticsQuery.isPending ? (
          <p className="mt-3 text-sm text-muted-foreground">
            Đang tải dữ liệu...
          </p>
        ) : areaRows.length === 0 ? (
          <p className="mt-3 text-sm text-muted-foreground">
            Không có dữ liệu khu vực.
          </p>
        ) : (
          <div className="mt-3 h-[360px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={areaRows}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis
                  dataKey="label"
                  interval={0}
                  angle={-20}
                  textAnchor="end"
                  height={80}
                />
                <YAxis />
                <Tooltip />
                <Legend />
                <Bar
                  dataKey="count"
                  fill="var(--color-chart-2)"
                  name="Số đơn"
                />
              </BarChart>
            </ResponsiveContainer>
          </div>
        )}
      </section>

      {f.s ? (
        <p className="text-sm text-muted-foreground">
          Đang lọc theo trạng thái:{' '}
          <strong>{statusLabel(f.s)}</strong>.
        </p>
      ) : null}
    </div>
  );
}

function StatCard({ title, value }: { title: string; value: string }) {
  return (
    <div className="rounded-md border border-border bg-card px-4 py-3">
      <p className="text-sm text-muted-foreground">{title}</p>
      <p className="mt-0 text-xl leading-snug font-bold">{value}</p>
    </div>
  );
}

// src/routes/admin/statistics/+page.svelte
<script lang="ts">
	import { createQuery } from '@tanstack/svelte-query';
	import { scaleBand } from 'd3-scale';
	import { BarChart } from 'layerchart';
	import * as Chart from '$lib/components/ui/chart/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Card from '$lib/components/ui/card/index.js';
	import * as Select from '$lib/components/ui/select/index.js';
	import * as Tabs from '$lib/components/ui/tabs/index.js';
	import { formatCurrency, statusLabel } from '$lib/utils/format';

	type StatisticsResponse = {
		revenue: {
			monthly: Array<{ month: number; total: number; count: number }>;
			total: number;
		};
		ordersByArea: {
			byDistrict: Array<{ district: string; count: number; total: number }>;
			byWard: Array<{ district: string; ward: string; count: number; total: number }>;
		};
		summary: {
			totalOrders: number;
			totalRevenue: number;
			avgOrderValue: number;
		};
	};

	let { data } = $props<{
		data: {
			currentYear: number;
			yearOptions: number[];
			statusOptions: Array<{ label: string; value: string }>;
		};
	}>();

	let loading = $state(false);
	let year = $state('');
	let month = $state('');
	let status = $state('');
	let submittedYear = $state('');
	let submittedMonth = $state('');
	let submittedStatus = $state('');
	let areaTab = $state<'district' | 'ward'>('district');
	let stats = $state<StatisticsResponse>({ revenue: { monthly: [], total: 0 }, ordersByArea: { byDistrict: [], byWard: [] }, summary: { totalOrders: 0, totalRevenue: 0, avgOrderValue: 0 } });

	const monthOptions = [
		{ label: 'Cả năm', value: '' },
		...Array.from({ length: 12 }, (_, index) => ({
			label: `Tháng ${index + 1}`,
			value: String(index + 1)
		}))
	];

	const areaRows = $derived(
		areaTab === 'district'
			? stats.ordersByArea.byDistrict.map((row) => ({
					name: row.district,
					subLabel: '',
					count: row.count,
					total: row.total
				}))
			: stats.ordersByArea.byWard.map((row) => ({
					name: row.ward,
					subLabel: row.district,
					count: row.count,
					total: row.total
				}))
	);

	$effect(() => {
		if (!year) {
			year = String(data.currentYear);
			submittedYear = String(data.currentYear);
		}
	});

	const statisticsQuery = createQuery(() => ({
		queryKey: ['admin', 'statistics', submittedYear, submittedMonth, submittedStatus],
		queryFn: async () => {
			const params = new URLSearchParams();
			if (submittedYear) params.set('year', submittedYear);
			if (submittedMonth) params.set('month', submittedMonth);
			if (submittedStatus) params.set('status', submittedStatus);
			const response = await fetch(`/api/admin/statistics?${params.toString()}`);
			const payload = await response.json();
			if (!response.ok) throw new Error(payload?.message ?? 'Không tải được thống kê');
			return payload as StatisticsResponse;
		}
	}));

	$effect(() => {
		loading = statisticsQuery.isPending;
		if (statisticsQuery.data) {
			stats = statisticsQuery.data;
		}
	});

	function loadStatistics() {
		submittedYear = year;
		submittedMonth = month;
		submittedStatus = status;
	}

	const revenueChartData = $derived(
		stats.revenue.monthly.map((row) => ({ month: `T${row.month}`, revenue: row.total, orders: row.count }))
	);

	const revenueChartConfig = {
		revenue: {
			label: 'Doanh thu',
			color: 'var(--chart-1)'
		}
	} satisfies Chart.ChartConfig;

	const areaChartData = $derived(
		areaRows.map((row) => ({
			label: row.subLabel ? `${row.name} (${row.subLabel})` : row.name,
			count: row.count,
			total: row.total
		}))
	);

	const areaChartConfig = {
		count: {
			label: 'Số đơn',
			color: 'var(--chart-2)'
		}
	} satisfies Chart.ChartConfig;
</script>

<main class="container-shell space-y-5">
	<div class="flex flex-wrap items-end justify-between gap-3">
		<div>
			<h1 class="text-3xl font-bold">Thống kê</h1>
			<p class="mt-1 text-sm text-muted-foreground">Doanh thu, số lượng đơn và phân bổ theo khu vực.</p>
		</div>
		<div class="flex flex-wrap gap-2">
			<Select.Root type="single" bind:value={year}>
				<Select.Trigger class="w-[140px]">
					{year || 'Năm'}
				</Select.Trigger>
				<Select.Content>
					{#each data.yearOptions as yearOption}
						<Select.Item value={String(yearOption)} label={String(yearOption)}>{yearOption}</Select.Item>
					{/each}
				</Select.Content>
			</Select.Root>
			<Select.Root type="single" bind:value={month}>
				<Select.Trigger class="w-[140px]">
					{monthOptions.find((option) => option.value === month)?.label ?? 'Tháng'}
				</Select.Trigger>
				<Select.Content>
					{#each monthOptions as option}
						<Select.Item value={option.value} label={option.label}>{option.label}</Select.Item>
					{/each}
				</Select.Content>
			</Select.Root>
			<Select.Root type="single" bind:value={status}>
				<Select.Trigger class="w-[220px]">
					{data.statusOptions.find((option: { label: string; value: string }) => option.value === status)?.label ?? 'Tất cả trạng thái'}
				</Select.Trigger>
				<Select.Content>
					{#each data.statusOptions as option}
						<Select.Item value={option.value} label={option.label}>{option.label}</Select.Item>
					{/each}
				</Select.Content>
			</Select.Root>
			<Button type="button" onclick={loadStatistics}>Lọc</Button>
		</div>
	</div>

	{#if statisticsQuery.isError}
		<div class="rounded-md border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">
			{statisticsQuery.error?.message ?? 'Không tải được thống kê'}
		</div>
	{/if}

	<div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
		<Card.Root><Card.Content class="px-5 py-1"><p class="text-sm text-muted-foreground">Tổng doanh thu</p><p class="mt-0 text-xl leading-tight font-bold">{formatCurrency(stats.summary.totalRevenue)}</p></Card.Content></Card.Root>
		<Card.Root><Card.Content class="px-5 py-1"><p class="text-sm text-muted-foreground">Tổng số đơn</p><p class="mt-0 text-xl leading-tight font-bold">{stats.summary.totalOrders}</p></Card.Content></Card.Root>
		<Card.Root><Card.Content class="px-5 py-1"><p class="text-sm text-muted-foreground">Giá trị đơn trung bình</p><p class="mt-0 text-xl leading-tight font-bold">{formatCurrency(stats.summary.avgOrderValue)}</p></Card.Content></Card.Root>
	</div>

	<section class="rounded-md border bg-card p-4">
		<h2 class="text-xl font-semibold">Doanh thu theo tháng</h2>
		{#if loading}
			<p class="mt-3 text-sm text-muted-foreground">Đang tải dữ liệu...</p>
		{:else if stats.revenue.monthly.length === 0}
			<p class="mt-3 text-sm text-muted-foreground">Không có dữ liệu.</p>
		{:else}
			<div class="mt-3 rounded-xl border p-3">
				<Chart.Container config={revenueChartConfig} class="min-h-[300px] w-full">
					<BarChart
						data={revenueChartData}
						xScale={scaleBand().padding(0.25)}
						x="month"
						y="revenue"
						axis="x"
						series={[{ key: 'revenue', label: 'Doanh thu', color: 'var(--color-revenue)' }]}
					>
						{#snippet tooltip()}
							<Chart.Tooltip />
						{/snippet}
					</BarChart>
				</Chart.Container>
			</div>
		{/if}
	</section>

	<section class="rounded-md border bg-card p-4">
		<div class="flex flex-wrap items-center justify-between gap-2">
			<h2 class="text-xl font-semibold">Số lượng theo khu vực</h2>
			<Tabs.Root value={areaTab} onValueChange={(value) => (areaTab = value as 'district' | 'ward')}>
				<Tabs.List>
					<Tabs.Trigger value="district">Quận/Huyện</Tabs.Trigger>
					<Tabs.Trigger value="ward">Phường/Xã</Tabs.Trigger>
				</Tabs.List>
			</Tabs.Root>
		</div>

		{#if loading}
			<p class="mt-3 text-sm text-muted-foreground">Đang tải dữ liệu...</p>
		{:else if areaRows.length === 0}
			<p class="mt-3 text-sm text-muted-foreground">Không có dữ liệu khu vực.</p>
		{:else}
			<div class="mt-3 rounded-xl border p-3">
				<Chart.Container config={areaChartConfig} class="min-h-[320px] w-full">
					<BarChart
						data={areaChartData}
						xScale={scaleBand().padding(0.2)}
						x="label"
						y="count"
						axis="x"
						series={[{ key: 'count', label: 'Số đơn', color: 'var(--color-count)' }]}
					>
						{#snippet tooltip()}
							<Chart.Tooltip />
						{/snippet}
					</BarChart>
				</Chart.Container>
			</div>
		{/if}
	</section>

	{#if status}
		<p class="text-sm text-muted-foreground">Đang lọc theo trạng thái: <strong>{statusLabel(status)}</strong>.</p>
	{/if}
</main>
