// src/lib/components/admin/MenuItemForm.svelte
<script lang="ts">
	import { MENU_IMAGE } from '$lib/constants/assets';
	import { formatCurrencyInput, parseCurrencyInput } from '$lib/utils/format';
	import { Button } from '$lib/components/ui/button/index.js';
	import { Checkbox } from '$lib/components/ui/checkbox/index.js';
	import * as Dialog from '$lib/components/ui/dialog/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import { Label } from '$lib/components/ui/label/index.js';
	import * as Select from '$lib/components/ui/select/index.js';
	import { Textarea } from '$lib/components/ui/textarea/index.js';

	type CategoryOption = { id: string; name: string };
	type MediaEntry = { type: 'image' | 'video'; url: string; altText?: string | null };
	type MenuItemInput = {
		id?: string;
		name: string;
		category_id: string;
		description?: string | null;
		ingredients?: string | null;
		note?: string | null;
		preparation_time_minutes?: number | null;
		thumbnail_url?: string | null;
		is_topping?: boolean;
		sort_order?: number;
		media?: { type: 'image' | 'video'; url: string; alt_text?: string | null }[];
		variants?: {
			id?: string;
			name: string;
			price: number;
			serves_min?: number | null;
			serves_max?: number | null;
			is_default?: boolean;
		}[];
	};
	type VariantForm = {
		id?: string;
		name: string;
		price: string;
	};

	let { open = false, categories = [], item = null, onClose, onSaved } = $props<{
		open?: boolean;
		categories?: CategoryOption[];
		item?: MenuItemInput | null;
		onClose?: () => void;
		onSaved?: (savedItem?: any) => void;
	}>();

	const isEdit = $derived(Boolean(item?.id));

	let lastKey = $state('');
	let saving = $state(false);
	let uploading = $state(false);
	let message = $state('');

	let form = $state({
		name: '',
		categoryId: '',
		description: '',
		ingredients: '',
		note: '',
		preparationTimeMinutes: '',
		thumbnailUrl: MENU_IMAGE,
		isTopping: false,
		sortOrder: 99
	});
	let media = $state<MediaEntry[]>([]);
	let variants = $state<VariantForm[]>([]);

	function createEmptyVariant(): VariantForm {
		return {
			name: '',
			price: ''
		};
	}

	function resetForm() {
		form.name = item?.name ?? '';
		form.categoryId = item?.category_id ?? categories[0]?.id ?? '';
		form.description = item?.description ?? '';
		form.ingredients = item?.ingredients ?? '';
		form.note = item?.note ?? '';
		form.preparationTimeMinutes =
			typeof item?.preparation_time_minutes === 'number' ? String(item.preparation_time_minutes) : '';
		form.thumbnailUrl = item?.thumbnail_url ?? MENU_IMAGE;
		form.isTopping = Boolean(item?.is_topping);
		form.sortOrder = item?.sort_order ?? 99;
		media =
			item?.media?.map((entry: { type: 'image' | 'video'; url: string; alt_text?: string | null }) => ({
				type: entry.type,
				url: entry.url,
				altText: entry.alt_text ?? null
			})) ?? [];
		const parsedVariants =
			item?.variants?.map((entry: { id?: string; name: string; price: number; serves_min?: number | null; serves_max?: number | null; is_default?: boolean }) => ({
				id: entry.id,
				name: entry.name ?? '',
				price: typeof entry.price === 'number' ? formatCurrencyInput(String(entry.price)) : ''
			})) ?? [];
		variants = parsedVariants.length > 0 ? parsedVariants : [createEmptyVariant()];
		message = '';
	}

	$effect(() => {
		const key = `${open}-${item?.id ?? 'new'}-${categories.length}`;
		if (key === lastKey || !open) return;
		lastKey = key;
		resetForm();
	});

	function addMediaEntries(entries: MediaEntry[]) {
		media = [...media, ...entries];
		const firstImage = entries.find((entry) => entry.type === 'image');
		if (firstImage && (!form.thumbnailUrl || form.thumbnailUrl === MENU_IMAGE)) {
			form.thumbnailUrl = firstImage.url;
		}
	}

	async function uploadSelectedFiles(event: Event) {
		const input = event.currentTarget as HTMLInputElement;
		const files = Array.from(input.files ?? []);
		if (files.length === 0) return;

		uploading = true;
		message = '';

		const formData = new FormData();
		for (const file of files) {
			formData.append('files', file);
		}

		const res = await fetch('/api/admin/upload', {
			method: 'POST',
			body: formData
		});
		const data = await res.json();
		uploading = false;
		input.value = '';

		if (!res.ok) {
			message = data.message ?? 'Upload thất bại';
			return;
		}

		addMediaEntries(data.files ?? []);
	}

	async function uploadThumbnailFile(event: Event) {
		const input = event.currentTarget as HTMLInputElement;
		const file = input.files?.[0];
		if (!file) return;

		uploading = true;
		message = '';

		const formData = new FormData();
		formData.append('files', file);

		const res = await fetch('/api/admin/upload', {
			method: 'POST',
			body: formData
		});
		const data = await res.json();
		uploading = false;
		input.value = '';

		if (!res.ok) {
			message = data.message ?? 'Upload thumbnail thất bại';
			return;
		}

		const uploadedFiles = (data.files ?? []) as MediaEntry[];
		const firstImage = uploadedFiles.find((entry) => entry.type === 'image');
		if (!firstImage?.url) {
			message = 'Không tìm thấy ảnh hợp lệ sau khi upload.';
			return;
		}

		form.thumbnailUrl = firstImage.url;
	}

	function removeMedia(index: number) {
		media = media.filter((_, i) => i !== index);
	}

	function setThumbnail(url: string) {
		form.thumbnailUrl = url;
	}

	function addVariant() {
		variants = [...variants, createEmptyVariant()];
	}

	function removeVariant(index: number) {
		const next = variants.filter((_, currentIndex) => currentIndex !== index);
		if (next.length === 0) {
			variants = [createEmptyVariant()];
			return;
		}
		variants = [...next];
	}

	function handleVariantPriceInput(index: number, event: Event) {
		const input = event.currentTarget as HTMLInputElement;
		variants[index].price = formatCurrencyInput(input.value);
	}

	function handleVariantPriceChange(index: number) {
		variants[index].price = formatCurrencyInput(variants[index].price);
	}

	async function submit() {
		if (!form.name.trim() || !form.categoryId) {
			message = 'Vui lòng nhập tên món và chọn danh mục.';
			return;
		}

		saving = true;
		message = '';

		const normalizedVariants = variants.map((entry) => ({
			name: entry.name.trim(),
			price: parseCurrencyInput(entry.price)
		}));
		if (normalizedVariants.length === 0) {
			saving = false;
			message = 'Cần tối thiểu một biến thể giá.';
			return;
		}
		for (const entry of normalizedVariants) {
			if (!entry.name) {
				saving = false;
				message = 'Tên biến thể không được để trống.';
				return;
			}
			if (entry.price === null || !Number.isFinite(entry.price) || entry.price < 0) {
				saving = false;
				message = 'Giá biến thể không hợp lệ.';
				return;
			}
		}

		const payload = {
			name: form.name.trim(),
			categoryId: form.categoryId,
			description: form.description.trim() || null,
			ingredients: form.ingredients.trim() || null,
			note: form.note.trim() || null,
			preparationTimeMinutes:
				form.preparationTimeMinutes === '' ? null : Math.max(0, Number(form.preparationTimeMinutes || 0)),
			thumbnailUrl: form.thumbnailUrl.trim() || null,
			isTopping: form.isTopping,
			sortOrder: Number(form.sortOrder || 0),
			variants: normalizedVariants.map((entry, index) => ({
				name: entry.name,
				price: Math.round(entry.price as number),
				isDefault: index === 0
			})),
			media: media.map((entry) => ({
				type: entry.type,
				url: entry.url,
				altText: entry.altText ?? null
			}))
		};

		const endpoint = isEdit ? `/api/admin/menu/${item?.id}` : '/api/admin/menu';
		const method = isEdit ? 'PATCH' : 'POST';
		const res = await fetch(endpoint, {
			method,
			headers: { 'content-type': 'application/json' },
			body: JSON.stringify(payload)
		});
		const data = await res.json();
		saving = false;

		if (!res.ok) {
			message = data.message ?? 'Không lưu được món';
			return;
		}

		onSaved?.(data.item);
		onClose?.();
	}
</script>

<Dialog.Root open={open} onOpenChange={(nextOpen) => !nextOpen && onClose?.()}>
	<Dialog.Portal>
		<Dialog.Overlay />
		<Dialog.Content class="max-h-[90vh] overflow-y-auto sm:max-w-3xl">
			<Dialog.Header>
				<Dialog.Title>{isEdit ? 'Chỉnh sửa món' : 'Thêm món mới'}</Dialog.Title>
			</Dialog.Header>

			<div class="mt-2 grid gap-4 sm:grid-cols-2">
				<div class="grid gap-2 sm:col-span-2">
					<Label for="menu-name">Tên món</Label>
					<Input id="menu-name" bind:value={form.name} />
				</div>

				<div class="grid gap-2">
					<Label for="menu-category">Danh mục</Label>
					<Select.Root type="single" bind:value={form.categoryId}>
						<Select.Trigger id="menu-category" class="w-full">
							{categories.find((category: CategoryOption) => category.id === form.categoryId)?.name ?? 'Chọn danh mục'}
						</Select.Trigger>
						<Select.Content>
							{#each categories as category}
								<Select.Item value={category.id} label={category.name}>{category.name}</Select.Item>
							{/each}
						</Select.Content>
					</Select.Root>
				</div>

				<div class="grid gap-2">
					<Label for="menu-sort-order">Thứ tự hiển thị</Label>
					<Input id="menu-sort-order" type="number" bind:value={form.sortOrder} />
				</div>

				<div class="grid gap-2 sm:col-span-2">
					<Label for="menu-description">Mô tả</Label>
					<Textarea id="menu-description" class="min-h-24" bind:value={form.description} />
				</div>

				<div class="grid gap-2 sm:col-span-2">
					<Label for="menu-ingredients">Nguyên liệu</Label>
					<Textarea id="menu-ingredients" class="min-h-24" bind:value={form.ingredients} />
				</div>

				<div class="grid gap-2 sm:col-span-2">
					<Label for="menu-note">Note nhà hàng</Label>
					<Textarea
						id="menu-note"
						class="min-h-20"
						bind:value={form.note}
						placeholder="Ví dụ: Món cần 30-35 phút chuẩn bị khi quán đông."
					/>
				</div>

				<div class="grid gap-2">
					<Label for="menu-prep-time">Thời gian chuẩn bị (phút)</Label>
					<Input
						id="menu-prep-time"
						type="number"
						min="0"
						step="1"
						bind:value={form.preparationTimeMinutes}
						placeholder="Ví dụ: 30"
					/>
				</div>

				<div class="grid gap-2 sm:col-span-2">
					<Label>Thumbnail</Label>
					<div class="rounded-xl border bg-muted/40 p-3">
						<div class="flex flex-col gap-3 sm:flex-row sm:items-center">
							<a
								href={form.thumbnailUrl || MENU_IMAGE}
								target="_blank"
								rel="noopener noreferrer"
								class="inline-flex w-fit"
								title="Mở ảnh ở tab mới"
							>
								<img
									src={form.thumbnailUrl || MENU_IMAGE}
									alt="Thumbnail preview"
									class="h-24 w-24 rounded-lg border bg-background object-cover"
								/>
							</a>
							<div class="flex-1 space-y-2">
								<div class="flex flex-wrap gap-2">
									<label class="inline-flex">
										<Button variant="outline" class="cursor-pointer" type="button">
											<input class="hidden" type="file" accept="image/*" onchange={uploadThumbnailFile} />
											{uploading ? 'Đang upload...' : 'Upload thumbnail'}
										</Button>
									</label>
									<Button variant="outline" type="button" onclick={() => (form.thumbnailUrl = MENU_IMAGE)}>
										Dùng ảnh mặc định
									</Button>
								</div>
								<p class="text-xs text-muted-foreground">Bấm vào ảnh để mở preview ở tab mới.</p>
							</div>
						</div>
					</div>
				</div>

				<div class="flex items-center gap-2">
					<Checkbox id="menu-is-topping" bind:checked={form.isTopping} />
					<Label for="menu-is-topping">Là topping</Label>
				</div>
			</div>

			<section class="mt-5 rounded-xl border bg-muted/40 p-4">
				<div class="flex flex-wrap items-center justify-between gap-2">
					<h3 class="font-semibold">Biến thể giá</h3>
					<Button variant="outline" size="sm" type="button" onclick={addVariant}>Thêm biến thể</Button>
				</div>
				<div class="mt-3 space-y-3">
					{#each variants as variant, index}
						<div class="rounded-lg border bg-background p-3">
							<div class="grid gap-3 sm:grid-cols-2">
								<div class="grid gap-2">
									<Label for={`variant-name-${index}`}>Loại món</Label>
									<Input id={`variant-name-${index}`} bind:value={variant.name} placeholder="Ví dụ: Lẩu 2-3 người ăn" />
								</div>
								<div class="grid gap-2">
									<Label for={`variant-price-${index}`}>Giá (VND)</Label>
									<Input
										id={`variant-price-${index}`}
										type="text"
										inputmode="numeric"
										placeholder="Ví dụ: 120000"
										value={variant.price}
										oninput={(event) => handleVariantPriceInput(index, event)}
										onchange={() => handleVariantPriceChange(index)}
										onblur={() => handleVariantPriceChange(index)}
									/>
								</div>
							</div>
							<div class="mt-3 flex justify-end">
								<Button variant="destructive" size="sm" type="button" onclick={() => removeVariant(index)}>
									Xóa biến thể
								</Button>
							</div>
						</div>
					{/each}
				</div>
			</section>

			<section class="mt-5 rounded-xl border bg-muted/40 p-4">
				<div class="flex flex-wrap items-center justify-between gap-2">
					<h3 class="font-semibold">Hình ảnh / video</h3>
					<label class="inline-flex">
						<Button variant="outline" class="cursor-pointer" type="button">
							<input class="hidden" type="file" accept="image/*,video/*" multiple onchange={uploadSelectedFiles} />
							{uploading ? 'Đang upload...' : 'Upload files'}
						</Button>
					</label>
				</div>

				{#if media.length === 0}
					<p class="mt-2 text-sm text-muted-foreground">Chưa có media. Có thể upload nhiều ảnh/video cùng lúc.</p>
				{:else}
					<div class="mt-3 grid gap-3 sm:grid-cols-2">
						{#each media as entry, index}
							<div class="rounded-xl border bg-background p-2">
								{#if entry.type === 'image'}
									<a href={entry.url} target="_blank" rel="noopener noreferrer" class="block" title="Mở ảnh ở tab mới">
										<img src={entry.url} alt="" class="h-28 w-full rounded-lg object-cover" />
									</a>
								{:else}
									<a
										href={entry.url}
										target="_blank"
										rel="noopener noreferrer"
										class="flex h-28 w-full items-center justify-center rounded-lg bg-muted text-sm text-muted-foreground"
										title="Mở media ở tab mới"
									>
										Video media
									</a>
								{/if}
								<div class="mt-2 flex gap-2">
									<Button variant="outline" size="sm" type="button" onclick={() => setThumbnail(entry.url)}>
										Đặt làm thumbnail
									</Button>
									<Button variant="destructive" size="sm" type="button" onclick={() => removeMedia(index)}>
										Xóa
									</Button>
								</div>
							</div>
						{/each}
					</div>
				{/if}
			</section>

			<Dialog.Footer class="mt-5">
				<Button variant="outline" type="button" onclick={onClose}>Hủy</Button>
				<Button type="button" onclick={submit} disabled={saving || uploading}>
					{saving ? 'Đang lưu...' : isEdit ? 'Lưu thay đổi' : 'Tạo món'}
				</Button>
			</Dialog.Footer>

			{#if message}
				<p class="mt-3 rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive">{message}</p>
			{/if}
		</Dialog.Content>
	</Dialog.Portal>
</Dialog.Root>

// src/components/admin/menu-item-form.tsx
'use client';

import { useEffect, useMemo, useState } from 'react';
import { formatCurrencyInput, parseCurrencyInput } from '@/lib/utils/format';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';

type CategoryOption = { id: string; name: string };
type MediaEntry = {
  type: 'image' | 'video';
  url: string;
  altText?: string | null;
};
type MenuVariant = {
  id?: string;
  name: string;
  price: number;
  serves_min?: number | null;
  serves_max?: number | null;
  is_default?: boolean;
};
type MenuItemInput = {
  id?: string;
  name: string;
  category_id: string;
  description?: string | null;
  ingredients?: string | null;
  note?: string | null;
  preparation_time_minutes?: number | null;
  thumbnail_url?: string | null;
  is_topping?: boolean;
  sort_order?: number;
  variants?: MenuVariant[];
  media?: { type: 'image' | 'video'; url: string; alt_text?: string | null }[];
};

type VariantForm = { name: string; price: string };

type Props = {
  open: boolean;
  categories: CategoryOption[];
  item?: MenuItemInput | null;
  onClose: () => void;
  onSaved?: (savedItem?: unknown) => void;
};

const EMPTY_VARIANT = { name: '', price: '' };
const DEFAULT_MENU_IMAGE = '/logo.png';

export function MenuItemForm({
  open,
  categories,
  item,
  onClose,
  onSaved,
}: Props) {
  const isEdit = Boolean(item?.id);
  const [saving, setSaving] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [message, setMessage] = useState('');
  const [name, setName] = useState('');
  const [categoryId, setCategoryId] = useState('');
  const [description, setDescription] = useState('');
  const [ingredients, setIngredients] = useState('');
  const [note, setNote] = useState('');
  const [preparationTimeMinutes, setPreparationTimeMinutes] = useState('');
  const [thumbnailUrl, setThumbnailUrl] = useState(DEFAULT_MENU_IMAGE);
  const [isTopping, setIsTopping] = useState(false);
  const [sortOrder, setSortOrder] = useState('99');
  const [variants, setVariants] = useState<VariantForm[]>([EMPTY_VARIANT]);
  const [media, setMedia] = useState<MediaEntry[]>([]);

  useEffect(() => {
    if (!open) return;
    setName(item?.name ?? '');
    setCategoryId(item?.category_id ?? categories[0]?.id ?? '');
    setDescription(item?.description ?? '');
    setIngredients(item?.ingredients ?? '');
    setNote(item?.note ?? '');
    setPreparationTimeMinutes(
      typeof item?.preparation_time_minutes === 'number'
        ? String(item.preparation_time_minutes)
        : '',
    );
    setThumbnailUrl(item?.thumbnail_url ?? DEFAULT_MENU_IMAGE);
    setIsTopping(Boolean(item?.is_topping));
    setSortOrder(String(item?.sort_order ?? 99));
    setMedia(
      (item?.media ?? []).map((entry) => ({
        type: entry.type,
        url: entry.url,
        altText: entry.alt_text ?? null,
      })),
    );
    const nextVariants = (item?.variants ?? []).map((entry) => ({
      name: entry.name ?? '',
      price: formatCurrencyInput(String(entry.price ?? '')),
    }));
    setVariants(nextVariants.length > 0 ? nextVariants : [EMPTY_VARIANT]);
    setMessage('');
  }, [open, item, categories]);

  const normalizedVariants = useMemo(
    () =>
      variants.map((entry) => ({
        name: entry.name.trim(),
        price: parseCurrencyInput(entry.price),
      })),
    [variants],
  );

  function addVariant() {
    setVariants((prev) => [...prev, EMPTY_VARIANT]);
  }

  function removeVariant(index: number) {
    setVariants((prev) => {
      const next = prev.filter((_, current) => current !== index);
      return next.length > 0 ? next : [EMPTY_VARIANT];
    });
  }

  function updateVariant(index: number, next: VariantForm) {
    setVariants((prev) =>
      prev.map((entry, current) => (current === index ? next : entry)),
    );
  }

  function addUploadedEntries(entries: MediaEntry[]) {
    setMedia((prev) => [...prev, ...entries]);
    const firstImage = entries.find((entry) => entry.type === 'image');
    if (firstImage && (!thumbnailUrl || thumbnailUrl === DEFAULT_MENU_IMAGE)) {
      setThumbnailUrl(firstImage.url);
    }
  }

  async function uploadFiles(files: File[], setThumbnailOnly = false) {
    if (files.length === 0) return;
    setUploading(true);
    setMessage('');
    try {
      const formData = new FormData();
      files.forEach((file) => formData.append('files', file));
      const response = await fetch('/api/admin/upload', {
        method: 'POST',
        body: formData,
      });
      const payload = await response.json();
      if (!response.ok) {
        setMessage(payload.message ?? 'Upload thất bại');
        return;
      }
      const uploaded = (payload.files ?? []) as MediaEntry[];
      if (setThumbnailOnly) {
        const firstImage = uploaded.find((entry) => entry.type === 'image');
        if (!firstImage?.url) {
          setMessage('Không tìm thấy ảnh hợp lệ sau khi upload.');
          return;
        }
        setThumbnailUrl(firstImage.url);
        return;
      }
      addUploadedEntries(uploaded);
    } finally {
      setUploading(false);
    }
  }

  async function submit() {
    if (!name.trim() || !categoryId) {
      setMessage('Vui lòng nhập tên món và chọn danh mục.');
      return;
    }
    if (normalizedVariants.some((entry) => !entry.name)) {
      setMessage('Tên biến thể không được để trống.');
      return;
    }
    if (
      normalizedVariants.some(
        (entry) => entry.price === null || (entry.price ?? -1) < 0,
      )
    ) {
      setMessage('Giá biến thể không hợp lệ.');
      return;
    }

    setSaving(true);
    setMessage('');
    const payload = {
      name: name.trim(),
      categoryId,
      description: description.trim() || null,
      ingredients: ingredients.trim() || null,
      note: note.trim() || null,
      preparationTimeMinutes: preparationTimeMinutes
        ? Math.max(0, Number(preparationTimeMinutes))
        : null,
      thumbnailUrl: thumbnailUrl.trim() || null,
      isTopping,
      sortOrder: Number(sortOrder || 0),
      variants: normalizedVariants.map((entry, index) => ({
        name: entry.name,
        price: Math.round(entry.price ?? 0),
        isDefault: index === 0,
      })),
      media: media.map((entry) => ({
        type: entry.type,
        url: entry.url,
        altText: entry.altText ?? null,
      })),
    };

    try {
      const endpoint = isEdit
        ? `/api/admin/menu/${item?.id}`
        : '/api/admin/menu';
      const method = isEdit ? 'PATCH' : 'POST';
      const response = await fetch(endpoint, {
        method,
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(payload),
      });
      const result = await response.json();
      if (!response.ok) {
        setMessage(result.message ?? 'Không lưu được món');
        return;
      }
      onSaved?.(result.item);
      onClose();
    } finally {
      setSaving(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={(next) => !next && onClose()}>
      <DialogContent className="max-h-[90vh] max-w-4xl overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{isEdit ? 'Chỉnh sửa món' : 'Thêm món mới'}</DialogTitle>
          <DialogDescription>
            Cập nhật thông tin món, biến thể giá và media để hiển thị đúng trên
            menu.
          </DialogDescription>
        </DialogHeader>

        <div className="mt-4 grid gap-3 sm:grid-cols-2">
          <div className="grid gap-1 sm:col-span-2">
            <Label>Tên món</Label>
            <Input value={name} onChange={(e) => setName(e.target.value)} />
          </div>
          <div className="grid gap-1">
            <Label>Danh mục</Label>
            <Select value={categoryId} onValueChange={setCategoryId}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {categories.map((category) => (
                  <SelectItem key={category.id} value={category.id}>
                    {category.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="grid gap-1">
            <Label>Thứ tự hiển thị</Label>
            <Input
              type="number"
              value={sortOrder}
              onChange={(e) => setSortOrder(e.target.value)}
            />
          </div>
          <div className="grid gap-1 sm:col-span-2">
            <Label>Mô tả</Label>
            <Textarea
              className="min-h-20"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
            />
          </div>
          <div className="grid gap-1 sm:col-span-2">
            <Label>Nguyên liệu</Label>
            <Textarea
              className="min-h-20"
              value={ingredients}
              onChange={(e) => setIngredients(e.target.value)}
            />
          </div>
          <div className="grid gap-1 sm:col-span-2">
            <Label>Note nhà hàng</Label>
            <Textarea
              className="min-h-16"
              value={note}
              onChange={(e) => setNote(e.target.value)}
            />
          </div>
          <div className="grid gap-1">
            <Label>Thời gian chuẩn bị (phút)</Label>
            <Input
              type="number"
              value={preparationTimeMinutes}
              onChange={(e) => setPreparationTimeMinutes(e.target.value)}
            />
          </div>
          <div className="grid gap-2 sm:col-span-2">
            <Label>Thumbnail</Label>
            <div className="flex flex-wrap items-center gap-3 rounded-md border p-3">
              <img
                src={thumbnailUrl || DEFAULT_MENU_IMAGE}
                alt="Thumbnail preview"
                className="h-20 w-20 rounded-md object-cover"
              />
              <div className="flex flex-wrap gap-2">
                <Button asChild type="button" variant="outline">
                  <Label className="cursor-pointer">
                    <Input
                      className="hidden"
                      type="file"
                      accept="image/*"
                      onChange={(e) =>
                        uploadFiles(Array.from(e.target.files ?? []), true)
                      }
                    />
                    {uploading ? 'Đang upload...' : 'Upload thumbnail'}
                  </Label>
                </Button>
                <Button
                  type="button"
                  onClick={() => setThumbnailUrl(DEFAULT_MENU_IMAGE)}
                  variant="outline"
                >
                  Dùng ảnh mặc định
                </Button>
              </div>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Checkbox
              checked={isTopping}
              onCheckedChange={(value) => setIsTopping(value === true)}
            />
            <Label>Là topping</Label>
          </div>
        </div>

        <section className="mt-5 rounded-md border p-3">
          <div className="flex items-center justify-between gap-2">
            <h3 className="font-semibold">Biến thể giá</h3>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={addVariant}
            >
              Thêm biến thể
            </Button>
          </div>
          <div className="mt-3 space-y-2">
            {variants.map((variant, index) => (
              <div
                key={`${index}-${variant.name}`}
                className="rounded-md border p-3"
              >
                <div className="grid gap-2 sm:grid-cols-2">
                  <Input
                    placeholder="Tên biến thể"
                    value={variant.name}
                    onChange={(e) =>
                      updateVariant(index, { ...variant, name: e.target.value })
                    }
                  />
                  <Input
                    placeholder="Giá (VND)"
                    value={variant.price}
                    onChange={(e) =>
                      updateVariant(index, {
                        ...variant,
                        price: formatCurrencyInput(e.target.value),
                      })
                    }
                  />
                </div>
                <div className="mt-2 text-right">
                  <Button
                    type="button"
                    onClick={() => removeVariant(index)}
                    variant="destructive"
                    size="sm"
                  >
                    Xóa biến thể
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section className="mt-5 rounded-md border p-3">
          <div className="flex items-center justify-between gap-2">
            <h3 className="font-semibold">Hình ảnh / video</h3>
            <Button asChild type="button" variant="outline" size="sm">
              <Label className="cursor-pointer">
                <Input
                  className="hidden"
                  type="file"
                  accept="image/*,video/*"
                  multiple
                  onChange={(e) =>
                    uploadFiles(Array.from(e.target.files ?? []))
                  }
                />
                {uploading ? 'Đang upload...' : 'Upload files'}
              </Label>
            </Button>
          </div>
          <div className="mt-3 grid gap-3 sm:grid-cols-2">
            {media.map((entry, index) => (
              <div
                key={`${entry.url}-${index}`}
                className="rounded-md border p-2"
              >
                {entry.type === 'image' ? (
                  <img
                    src={entry.url}
                    alt=""
                    className="h-28 w-full rounded-md object-cover"
                  />
                ) : (
                  <a
                    href={entry.url}
                    target="_blank"
                    rel="noreferrer"
                    className="flex h-28 items-center justify-center rounded-md bg-muted text-sm text-muted-foreground"
                  >
                    Video media
                  </a>
                )}
                <div className="mt-2 flex gap-2">
                  <Button
                    type="button"
                    onClick={() => setThumbnailUrl(entry.url)}
                    variant="outline"
                    size="sm"
                  >
                    Đặt làm thumbnail
                  </Button>
                  <Button
                    type="button"
                    onClick={() =>
                      setMedia((prev) =>
                        prev.filter((_, current) => current !== index),
                      )
                    }
                    variant="destructive"
                    size="sm"
                  >
                    Xóa
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </section>

        {message ? (
          <p className="mt-4 rounded-md border border-destructive/50 bg-destructive/10 px-3 py-2 text-sm text-foreground">
            {message}
          </p>
        ) : null}

        <DialogFooter className="mt-5">
          <Button type="button" onClick={onClose} variant="outline">
            Hủy
          </Button>
          <Button type="button" onClick={submit} disabled={saving || uploading}>
            {saving ? 'Đang lưu...' : isEdit ? 'Lưu thay đổi' : 'Tạo món'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
