// src/routes/cart/+page.svelte
<script lang="ts">
	import { page } from '$app/state';
	import BottomNav from '$lib/components/BottomNav.svelte';
	import Footer from '$lib/components/Footer.svelte';
	import Header from '$lib/components/Header.svelte';
	import OrderConfirmModal from '$lib/components/OrderConfirmModal.svelte';
	import OrderForm from '$lib/components/OrderForm.svelte';
	import { HCMC_PROVINCE_NAME } from '$lib/data/provinces';
	import { cartStore, cartTotal } from '$lib/stores/cart';
	import { sessionStore } from '$lib/stores/session';
	import { formatCurrency } from '$lib/utils/format';
	import { goto } from '$app/navigation';

	type ScheduleOption = { value: string; label: string };
	type TimeSlotOption = { value: string; label: string; startHour: number; endHour: number };

	const TIME_SLOTS: TimeSlotOption[] = [
		{ value: '10:00-12:00', label: '10:00 - 12:00', startHour: 10, endHour: 12 },
		{ value: '12:00-14:00', label: '12:00 - 14:00', startHour: 12, endHour: 14 },
		{ value: '14:00-16:00', label: '14:00 - 16:00', startHour: 14, endHour: 16 },
		{ value: '16:00-18:00', label: '16:00 - 18:00', startHour: 16, endHour: 18 },
		{ value: '18:00-20:00', label: '18:00 - 20:00', startHour: 18, endHour: 20 }
	];

	function formatDatePart(value: number) {
		return String(value).padStart(2, '0');
	}

	function toVietnamClock(now: Date) {
		return new Date(now.getTime() + (7 * 60 + now.getTimezoneOffset()) * 60 * 1000);
	}

	function toVietnamDateString(vnDate: Date) {
		const year = vnDate.getUTCFullYear();
		const month = formatDatePart(vnDate.getUTCMonth() + 1);
		const day = formatDatePart(vnDate.getUTCDate());
		return `${year}-${month}-${day}`;
	}

	function getCutoffHour(vnDate: Date) {
		const dayOfWeek = vnDate.getUTCDay();
		return dayOfWeek === 0 || dayOfWeek === 6 ? 16 : 14;
	}

	function fromVietnamDateString(value: string) {
		return new Date(`${value}T00:00:00+07:00`);
	}

	function buildScheduleDateOptions(now: Date = new Date()): ScheduleOption[] {
		const vnNow = toVietnamClock(now);
		const startOffset = vnNow.getUTCHours() >= getCutoffHour(vnNow) ? 1 : 0;
		const options: ScheduleOption[] = [];
		for (let offset = startOffset; offset <= 7; offset += 1) {
			const vnDay = new Date(
				Date.UTC(vnNow.getUTCFullYear(), vnNow.getUTCMonth(), vnNow.getUTCDate() + offset)
			);
			const dateValue = toVietnamDateString(vnDay);
			const dateForLabel = new Date(`${dateValue}T00:00:00+07:00`);
			const labelDate = new Intl.DateTimeFormat('vi-VN', {
				weekday: 'long',
				day: '2-digit',
				month: '2-digit',
				timeZone: 'Asia/Ho_Chi_Minh'
			}).format(dateForLabel);
			options.push({
				value: dateValue,
				label: offset === 0 ? `Hôm nay (${labelDate})` : labelDate
			});
		}
		return options;
	}

	function buildScheduleSlotOptions(selectedDate: string, now: Date = new Date()): TimeSlotOption[] {
		if (!selectedDate) return [...TIME_SLOTS];
		const vnNow = toVietnamClock(now);
		const todayInVietnam = toVietnamDateString(vnNow);
		if (selectedDate !== todayInVietnam) return [...TIME_SLOTS];

		const selectedVnDate = fromVietnamDateString(selectedDate);
		const cutoffHour = getCutoffHour(selectedVnDate);
		const currentHour = vnNow.getUTCHours();

		return TIME_SLOTS.filter((slot) => slot.endHour <= cutoffHour && slot.endHour > currentHour);
	}

	const scheduleDateOptions = buildScheduleDateOptions();

	let form = $state({
		customerName: '',
		phone: '',
		website: '',
		province: '',
		district: '',
		ward: '',
		address: '',
		note: '',
		scheduledDate: scheduleDateOptions[0]?.value ?? '',
		scheduledSlot: TIME_SLOTS[0]?.value ?? ''
	});
	let scheduleSlotOptions = $derived(buildScheduleSlotOptions(form.scheduledDate));

	let submitting = $state(false);
	let showConfirm = $state(false);
	let errorMessage = $state('');
	const canonicalUrl = $derived(`${page.url.origin}/cart`);
	const selectedScheduleOption = $derived(
		scheduleDateOptions.find((option) => option.value === form.scheduledDate) ?? null
	);
	const selectedSlotOption = $derived(
		scheduleSlotOptions.find((option) => option.value === form.scheduledSlot) ?? null
	);

	$effect(() => {
		const hasSelectedDate = scheduleDateOptions.some((option) => option.value === form.scheduledDate);
		if (!hasSelectedDate) {
			form.scheduledDate = scheduleDateOptions[0]?.value ?? '';
		}
	});

	$effect(() => {
		const hasSelectedSlot = scheduleSlotOptions.some((option) => option.value === form.scheduledSlot);
		if (!hasSelectedSlot) {
			form.scheduledSlot = scheduleSlotOptions[0]?.value ?? '';
		}
	});

	function openConfirm() {
		errorMessage = '';
		if ($cartStore.length === 0) {
			errorMessage = 'Giỏ hàng đang trống.';
			return;
		}
		if (!form.customerName || !form.phone || !form.address || !form.district || !form.ward) {
			errorMessage = 'Vui lòng điền đầy đủ thông tin đặt món trước khi xác nhận.';
			return;
		}
		if (!form.scheduledDate || !form.scheduledSlot) {
			errorMessage = 'Vui lòng chọn ngày và khung giờ nhận món.';
			return;
		}
		if (form.province !== HCMC_PROVINCE_NAME) {
			errorMessage = 'Hiện tại quán chỉ hỗ trợ giao khu vực Thành phố Hồ Chí Minh.';
			return;
		}
		showConfirm = true;
	}

	async function submitOrder() {
		errorMessage = '';
		if ($cartStore.length === 0) {
			errorMessage = 'Giỏ hàng đang trống.';
			return;
		}

		submitting = true;
		try {
			const res = await fetch('/api/orders', {
				method: 'POST',
				headers: { 'content-type': 'application/json' },
				body: JSON.stringify({
					sessionId: sessionStore.getCurrent(),
					customerName: form.customerName,
					phone: form.phone.replace(/\s+/g, ''),
					website: form.website,
					province: form.province,
					district: form.district,
					ward: form.ward,
					address: form.address,
					note: form.note,
					scheduledDate: form.scheduledDate,
					scheduledSlot: form.scheduledSlot,
					items: $cartStore.map((line) => ({ variantId: line.variantId, quantity: line.quantity }))
				})
			});

			const data = await res.json();
			if (!res.ok) {
				errorMessage = data.message ?? 'Không thể tạo đơn hàng.';
				showConfirm = false;
				return;
			}

			cartStore.clear();
			await goto(`/orders/${data.orderId}`);
		} catch (error) {
			errorMessage = 'Kết nối thất bại, vui lòng thử lại.';
			showConfirm = false;
		} finally {
			submitting = false;
		}
	}
</script>

<svelte:head>
	<title>Giỏ hàng | Tiệm Lẩu Anh Hai</title>
	<meta
		name="description"
		content="Xem lại món đã chọn, cập nhật số lượng và hoàn tất đặt hàng tại Tiệm Lẩu Anh Hai."
	/>
	<link rel="canonical" href={canonicalUrl} />
	<meta name="robots" content="noindex, nofollow" />
</svelte:head>

<Header />

<main class="container-shell grid gap-6 py-6 lg:grid-cols-[1.1fr,0.9fr]">
	<section class="space-y-3">
		<h1 class="text-3xl font-bold">Giỏ hàng</h1>
		{#if $cartStore.length === 0}
			<p class="card-surface p-4 text-sm">
				Chưa có món nào trong giỏ.
				<button
					type="button"
					class="ml-1 font-medium text-orange-700 underline decoration-orange-300 underline-offset-2"
					onclick={() => goto('/menu')}
				>
					Xem menu
				</button>.
			</p>
		{:else}
			<div class="space-y-3">
				{#each $cartStore as line}
					<div class="card-surface p-3">
						<div class="flex items-start justify-between gap-3">
							<div>
								<p class="font-medium">{line.itemName}</p>
								<p class="text-xs text-slate-500">{line.variantName}</p>
								<p class="text-sm text-orange-700">{formatCurrency(line.price)}</p>
							</div>
							<div class="inline-flex items-center rounded-xl border border-orange-200">
								<button class="px-3 py-2" type="button" onclick={() => cartStore.updateQuantity(line.variantId, line.quantity - 1)}>-</button>
								<span class="min-w-9 text-center">{line.quantity}</span>
								<button class="px-3 py-2" type="button" onclick={() => cartStore.updateQuantity(line.variantId, line.quantity + 1)}>+</button>
							</div>
						</div>
					</div>
				{/each}
			</div>
		{/if}
	</section>

	<section class="card-surface p-4">
		<h2 class="text-2xl font-semibold">Thông tin đặt món</h2>
		<p class="mt-1 text-sm text-slate-600">Tổng tiền: <strong>{formatCurrency($cartTotal)}</strong></p>
		<div class="mt-4">
			<OrderForm model={form} dateOptions={scheduleDateOptions} slotOptions={scheduleSlotOptions} {submitting} />
		</div>
		{#if errorMessage}
			<p class="mt-3 text-sm text-red-700">{errorMessage}</p>
		{/if}
		<button class="btn-primary mt-4 w-full" type="button" onclick={openConfirm} disabled={submitting}>
			Xác nhận đặt món
		</button>
	</section>
</main>

{#if showConfirm}
	<OrderConfirmModal
		form={form}
		lines={$cartStore}
		totalAmount={$cartTotal}
		scheduledDateLabel={selectedScheduleOption?.label ?? form.scheduledDate}
		scheduledSlotLabel={selectedSlotOption?.label ?? form.scheduledSlot}
		{submitting}
		onCancel={() => (showConfirm = false)}
		onConfirm={submitOrder}
	/>
{/if}

<Footer />
<BottomNav />

// src/app/cart/page.tsx
'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Cart } from '@/components/Cart';
import { OrderForm, type OrderFormModel } from '@/components/OrderForm';
import { OrderConfirmModal } from '@/components/OrderConfirmModal';
import { BottomNav } from '@/components/BottomNav';
import { useCartStore, selectCartTotal } from '@/lib/stores/cart';
import { sessionStore } from '@/lib/stores/session';
import { Button } from '@/components/ui/button';

const SLOT_OPTIONS = [
  { value: '10:00-12:00', label: '10:00 - 12:00' },
  { value: '12:00-14:00', label: '12:00 - 14:00' },
  { value: '14:00-16:00', label: '14:00 - 16:00' },
  { value: '16:00-18:00', label: '16:00 - 18:00' },
  { value: '18:00-20:00', label: '18:00 - 20:00' },
];

function nextSevenDays() {
  return Array.from({ length: 7 }, (_, index) => {
    const date = new Date();
    date.setDate(date.getDate() + index);
    const value = date.toISOString().slice(0, 10);
    const label = date.toLocaleDateString('vi-VN', {
      weekday: 'short',
      day: '2-digit',
      month: '2-digit',
    });
    return { value, label };
  });
}

const EMPTY_FORM: OrderFormModel = {
  customerName: '',
  phone: '',
  website: '',
  province: 'Thành phố Hồ Chí Minh',
  district: '',
  ward: '',
  address: '',
  note: '',
  scheduledDate: '',
  scheduledSlot: '',
};

type MenuRuleItem = {
  id: string;
  name: string;
  block_today?: boolean;
  block_today_reason?: string | null;
  blocked_delivery_dates?: string[] | null;
  blocked_delivery_date_reasons?: Record<string, string> | null;
};

export default function CartPage() {
  const router = useRouter();
  const lines = useCartStore((state) => state.lines);
  const clear = useCartStore((state) => state.clear);
  const totalAmount = useCartStore(selectCartTotal);
  const [form, setForm] = useState<OrderFormModel>(EMPTY_FORM);
  const [invalidFields, setInvalidFields] = useState<string[]>([]);
  const [showConfirm, setShowConfirm] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState('');
  const [disabledDateReasons, setDisabledDateReasons] = useState<
    Record<string, string>
  >({});
  const dateOptions = useMemo(() => nextSevenDays(), []);
  const todayDateValue = dateOptions[0]?.value ?? '';

  useEffect(() => {
    let active = true;
    async function loadDisabledDates() {
      if (lines.length === 0) {
        if (active) setDisabledDateReasons({});
        return;
      }
      try {
        const response = await fetch('/api/menu', { cache: 'no-store' });
        const data = await response.json();
        if (!response.ok) return;
        const menuItems = (data?.menuItems ?? []) as MenuRuleItem[];
        const menuItemById = new Map(menuItems.map((item) => [item.id, item]));
        const selectedDates = new Set(dateOptions.map((option) => option.value));
        const reasonsByDate = new Map<string, Set<string>>();

        for (const line of lines) {
          const menuItem = menuItemById.get(line.itemId);
          if (!menuItem) continue;
          const itemLabel = menuItem.name;
          const todayReason =
            menuItem.block_today_reason?.trim() ||
            `Món "${itemLabel}" đang tạm ngưng giao hôm nay.`;
          if (menuItem.block_today && todayDateValue) {
            const reasons = reasonsByDate.get(todayDateValue) ?? new Set<string>();
            reasons.add(todayReason);
            reasonsByDate.set(todayDateValue, reasons);
          }
          for (const blockedDate of menuItem.blocked_delivery_dates ?? []) {
            if (!selectedDates.has(blockedDate)) continue;
            const reasonForDate = menuItem.blocked_delivery_date_reasons?.[
              blockedDate
            ]?.trim();
            const reasons = reasonsByDate.get(blockedDate) ?? new Set<string>();
            reasons.add(
              reasonForDate || `Món "${itemLabel}" không giao trong ngày này.`,
            );
            reasonsByDate.set(blockedDate, reasons);
          }
        }

        const nextReasons: Record<string, string> = {};
        for (const [dateValue, reasons] of reasonsByDate.entries()) {
          nextReasons[dateValue] = Array.from(reasons).join(' ');
        }
        if (active) setDisabledDateReasons(nextReasons);
      } catch {
        if (active) setDisabledDateReasons({});
      }
    }
    loadDisabledDates();
    return () => {
      active = false;
    };
  }, [dateOptions, lines, todayDateValue]);

  useEffect(() => {
    if (!form.scheduledDate) return;
    const blockedReason = disabledDateReasons[form.scheduledDate];
    if (!blockedReason) return;
    setForm((current) => ({ ...current, scheduledDate: '', scheduledSlot: '' }));
    setSubmitError(blockedReason);
  }, [disabledDateReasons, form.scheduledDate]);

  const validateBeforeConfirm = () => {
    const required: Array<keyof OrderFormModel> = [
      'customerName',
      'phone',
      'province',
      'district',
      'ward',
      'address',
      'scheduledDate',
      'scheduledSlot',
    ];
    const failed = required.filter((field) => !form[field]?.trim());
    setInvalidFields(failed as string[]);
    if (lines.length === 0) {
      setSubmitError('Giỏ hàng đang trống.');
      return false;
    }
    if (failed.length > 0) {
      setSubmitError('Vui lòng nhập đầy đủ thông tin bắt buộc.');
      return false;
    }
    const blockedReason = disabledDateReasons[form.scheduledDate];
    if (blockedReason) {
      setSubmitError(blockedReason);
      return false;
    }
    setSubmitError('');
    return true;
  };

  const submitOrder = async () => {
    setSubmitting(true);
    setSubmitError('');
    try {
      const sessionId = sessionStore.getCurrent();
      const res = await fetch('/api/orders', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({
          sessionId,
          customerName: form.customerName,
          phone: form.phone,
          province: form.province,
          district: form.district,
          ward: form.ward,
          address: form.address,
          note: form.note || null,
          website: form.website || null,
          scheduledDate: form.scheduledDate,
          scheduledSlot: form.scheduledSlot,
          items: lines.map((line) => ({
            variantId: line.variantId,
            quantity: line.quantity,
          })),
        }),
      });
      const data = await res.json();
      if (!res.ok) {
        setSubmitError(data?.message || 'Không thể tạo đơn hàng.');
        return;
      }
      clear();
      setShowConfirm(false);
      router.push(`/orders/${data.orderId}`);
    } catch {
      setSubmitError('Không thể kết nối tới máy chủ.');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <>
      <Header />
      <main className="container-shell py-8">
        <h1 className="text-3xl font-semibold">Giỏ hàng và đặt món</h1>
        <div className="mt-5 grid gap-6 lg:grid-cols-[1.1fr,1fr]">
          <section className="space-y-3">
            <h2 className="text-xl font-semibold">Giỏ hàng</h2>
            <Cart />
          </section>
          <section className="card-surface p-4">
            <h2 className="mb-4 text-xl font-semibold">Thông tin đặt hàng</h2>
            <OrderForm
              model={form}
              onChange={setForm}
              dateOptions={dateOptions}
              slotOptions={SLOT_OPTIONS}
              disabledDateReasons={disabledDateReasons}
              submitting={submitting}
              invalidFields={invalidFields}
            />
            {submitError ? (
              <p className="mt-3 text-sm text-destructive">{submitError}</p>
            ) : null}
            <Button
              type="button"
              className="mt-4 w-full"
              onClick={() => {
                if (validateBeforeConfirm()) setShowConfirm(true);
              }}
            >
              Xác nhận đặt món
            </Button>
          </section>
        </div>
      </main>
      <Footer />
      <BottomNav />
      <OrderConfirmModal
        open={showConfirm}
        form={form}
        lines={lines}
        totalAmount={totalAmount}
        scheduledDateLabel={
          dateOptions.find((entry) => entry.value === form.scheduledDate)?.label
        }
        scheduledSlotLabel={
          SLOT_OPTIONS.find((entry) => entry.value === form.scheduledSlot)
            ?.label
        }
        submitting={submitting}
        onCancel={() => setShowConfirm(false)}
        onConfirm={submitOrder}
      />
    </>
  );
}
