// src/app/orders/page.tsx
'use client';

import { useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { BottomNav } from '@/components/BottomNav';
import { OrderHistory } from '@/components/OrderHistory';
import { sessionStore } from '@/lib/stores/session';
import type { Order } from '@/lib/types';

type OrdersResponse = {
  orders: Order[];
};

export default function OrdersPage() {
  const sessionId = useMemo(() => sessionStore.getCurrent(), []);
  const { data, isLoading, isError, error } = useQuery({
    queryKey: ['orders', sessionId],
    queryFn: async (): Promise<OrdersResponse> => {
      const res = await fetch(
        `/api/orders?sessionId=${encodeURIComponent(sessionId)}`,
      );
      const json = await res.json();
      if (!res.ok)
        throw new Error(json?.message || 'Không thể tải danh sách đơn hàng.');
      return json;
    },
  });

  return (
    <>
      <Header />
      <main className="container-shell py-8">
        <h1 className="text-3xl font-semibold">Lịch sử đơn hàng</h1>
        {isLoading ? (
          <p className="mt-4 text-sm text-muted-foreground">
            Đang tải đơn hàng...
          </p>
        ) : null}
        {isError ? (
          <p className="mt-4 text-sm text-destructive">
            {(error as Error).message}
          </p>
        ) : null}
        <div className="mt-4">
          <OrderHistory orders={data?.orders ?? []} />
        </div>
      </main>
      <Footer />
      <BottomNav />
    </>
  );
}

// src/routes/orders/+page.svelte
<script lang="ts">
	import BottomNav from '$lib/components/BottomNav.svelte';
	import Footer from '$lib/components/Footer.svelte';
	import Header from '$lib/components/Header.svelte';
	import OrderHistory from '$lib/components/OrderHistory.svelte';
	import { sessionStore } from '$lib/stores/session';
	import type { Order } from '$lib/types';

	let loading = $state(true);
	let orders = $state<Order[]>([]);
	let errorMessage = $state('');

	async function loadOrders() {
		loading = true;
		errorMessage = '';
		try {
			const sessionId = sessionStore.getCurrent();
			const res = await fetch(`/api/orders?sessionId=${sessionId}`);
			const data = await res.json();
			if (!res.ok) {
				errorMessage = data.message ?? 'Không tải được đơn hàng.';
				return;
			}
			orders = data.orders;
		} catch (error) {
			errorMessage = 'Kết nối thất bại.';
		} finally {
			loading = false;
		}
	}

	$effect(() => {
		loadOrders();
	});
</script>

<svelte:head>
	<title>Lịch sử đơn hàng | Tiệm Lẩu Anh Hai</title>
</svelte:head>

<Header />
<main class="container-shell space-y-4 py-6">
	<div class="flex items-center justify-between">
		<h1 class="text-3xl font-bold">Lịch sử đơn hàng</h1>
		<button class="btn-secondary" type="button" onclick={loadOrders}>Làm mới</button>
	</div>

	{#if loading}
		<p class="card-surface p-4 text-sm">Đang tải dữ liệu...</p>
	{:else if errorMessage}
		<p class="card-surface p-4 text-sm text-red-700">{errorMessage}</p>
	{:else}
		<OrderHistory {orders} />
	{/if}
</main>

<Footer />
<BottomNav />
