// src/components/admin/admin-sidebar.tsx
'use client';

import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from '@/components/ui/sheet';

type AdminRole = 'super_admin' | 'manager';

type AdminSidebarProps = {
  adminEmail?: string;
  adminRole?: AdminRole;
  children: React.ReactNode;
};

export function AdminSidebar({
  adminEmail = 'Admin',
  adminRole = 'manager',
  children,
}: AdminSidebarProps) {
  const pathname = usePathname();
  const router = useRouter();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [loggingOut, setLoggingOut] = useState(false);

  const navItems = useMemo(() => {
    const items = [
      { href: '/admin', label: 'Dashboard' },
      { href: '/admin/statistics', label: 'Thống kê' },
      { href: '/admin/menu', label: 'Menu' },
      { href: '/admin/orders', label: 'Đơn hàng' },
    ];
    if (adminRole === 'super_admin') {
      items.push({ href: '/admin/employees', label: 'Nhân viên' });
    }
    items.push({ href: '/admin/settings', label: 'Cài đặt' });
    return items;
  }, [adminRole]);

  async function logout() {
    setLoggingOut(true);
    try {
      await fetch('/api/admin/auth/logout', { method: 'POST' });
    } finally {
      router.push('/admin/login');
      router.refresh();
      setLoggingOut(false);
    }
  }

  if (pathname === '/admin/login') {
    return <>{children}</>;
  }

  return (
    <div className="admin-shell">
      <aside className="admin-sidebar">
        <div className="admin-sidebar-section">
          <div className="flex items-center gap-3">
            <img
              src="/logo.png"
              alt="Logo Tiệm Lẩu Anh Hai"
              className="size-9 rounded-md object-contain"
            />
            <div>
              <p className="text-xs uppercase tracking-wide text-sidebar-foreground/70">
                Tiệm Lẩu Anh Hai
              </p>
              <p className="mt-1 text-xl font-semibold">Admin Panel</p>
            </div>
          </div>
          <p className="mt-2 truncate text-sm text-sidebar-foreground/80">
            {adminEmail}
          </p>
        </div>
        <div className="admin-sidebar-divider" />
        <nav className="admin-sidebar-nav flex-1">
          {navItems.map((item) => {
            const active =
              item.href === '/admin'
                ? pathname === item.href
                : pathname.startsWith(item.href);
            return (
              <Link
                key={item.href}
                href={item.href}
                prefetch={false}
                className={`admin-sidebar-link ${active ? 'admin-sidebar-link-active' : ''}`}
              >
                {item.label}
              </Link>
            );
          })}
        </nav>
        <div className="p-3">
          <Button
            type="button"
            onClick={logout}
            disabled={loggingOut}
            className="w-full"
          >
            {loggingOut ? 'Đang đăng xuất...' : 'Đăng xuất'}
          </Button>
        </div>
      </aside>

      <Sheet open={mobileOpen} onOpenChange={setMobileOpen}>
        <SheetContent
          side="left"
          className="w-[280px] border-r border-sidebar-border bg-sidebar p-0 text-sidebar-foreground sm:max-w-none"
        >
          <SheetHeader className="admin-sidebar-section pb-0">
            <SheetTitle className="sr-only">Admin Navigation</SheetTitle>
            <div className="flex items-center gap-3">
              <img
                src="/logo.png"
                alt="Logo Tiệm Lẩu Anh Hai"
                className="size-9 rounded-md object-contain"
              />
              <div>
                <p className="text-xs uppercase tracking-wide text-sidebar-foreground/70">
                  Tiệm Lẩu Anh Hai
                </p>
                <p className="mt-1 text-xl font-semibold">Admin Panel</p>
              </div>
            </div>
            <p className="mt-2 truncate text-sm text-sidebar-foreground/80">
              {adminEmail}
            </p>
          </SheetHeader>
          <div className="admin-sidebar-divider" />
          <nav className="admin-sidebar-nav">
            {navItems.map((item) => {
              const active =
                item.href === '/admin'
                  ? pathname === item.href
                  : pathname.startsWith(item.href);
              return (
                <Link
                  key={item.href}
                  href={item.href}
                  prefetch={false}
                  onClick={() => setMobileOpen(false)}
                  className={`admin-sidebar-link ${active ? 'admin-sidebar-link-active' : ''}`}
                >
                  {item.label}
                </Link>
              );
            })}
          </nav>
        </SheetContent>
      </Sheet>

      <div className="lg:pl-64">
        <header className="sticky top-0 z-30 border-b border-border bg-background/95 backdrop-blur">
          <div className="flex h-16 items-center justify-between gap-4 px-4 sm:px-6">
            <div className="flex items-center gap-3">
              <Button
                type="button"
                variant="outline"
                size="icon"
                onClick={() => setMobileOpen(true)}
                className="size-9 lg:hidden"
              >
                <svg
                  viewBox="0 0 20 20"
                  className="size-5 fill-current"
                  aria-hidden="true"
                >
                  <path d="M3 5h14v2H3V5Zm0 4h14v2H3V9Zm0 4h14v2H3v-2Z" />
                </svg>
              </Button>
              <div>
                <p className="text-sm text-muted-foreground">
                  Khu vực quản trị
                </p>
                <p className="font-semibold">Admin Dashboard</p>
              </div>
            </div>
            <p className="hidden text-sm text-muted-foreground sm:block">
              {adminEmail}
            </p>
          </div>
        </header>
        <main className="min-h-[calc(100dvh-4rem)] px-4 py-6 sm:px-6">
          {children}
        </main>
      </div>
    </div>
  );
}

// src/lib/components/admin/AdminSidebar.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Dialog from '$lib/components/ui/dialog/index.js';
	import { LOGO_IMAGE } from '$lib/constants/assets';
	import { Separator } from '$lib/components/ui/separator/index.js';
	import * as Sheet from '$lib/components/ui/sheet/index.js';

	let { adminEmail, adminRole = 'manager', open = false, onClose } = $props<{
		adminEmail: string;
		adminRole?: 'super_admin' | 'manager';
		open?: boolean;
		onClose?: () => void;
	}>();

	const navItems = $derived.by(() => {
		const items = [
			{ href: '/admin', label: 'Dashboard' },
			{ href: '/admin/statistics', label: 'Thống kê' },
			{ href: '/admin/menu', label: 'Menu' },
			{ href: '/admin/orders', label: 'Đơn hàng' }
		];
		if (adminRole === 'super_admin') {
			items.push({ href: '/admin/employees', label: 'Nhân viên' });
		}
		items.push({ href: '/admin/settings', label: 'Cài đặt' });
		return items;
	});

	let showLogoutConfirm = $state(false);

	async function logout() {
		await fetch('/api/admin/auth/logout', { method: 'POST' });
		window.location.href = '/admin/login';
	}

	function isActive(path: string) {
		if (path === '/admin') return page.url.pathname === path;
		return page.url.pathname.startsWith(path);
	}
</script>

<aside class="hidden w-64 flex-col border-r bg-[#2f1e14] text-orange-50 lg:fixed lg:inset-y-0 lg:left-0 lg:z-50 lg:flex">
	<div class="px-5 py-4">
		<div class="flex items-center gap-3">
			<img src={LOGO_IMAGE} alt="Logo Tiệm Lẩu Anh Hai" loading="eager" decoding="async" class="size-9 rounded-md object-contain" />
			<div>
				<p class="text-xs uppercase tracking-wide text-orange-200/70">Tiệm Lẩu Anh Hai</p>
				<p class="mt-1 text-xl font-semibold">Admin Panel</p>
			</div>
		</div>
		<p class="mt-2 truncate text-sm text-orange-100/80">{adminEmail}</p>
	</div>
	<Separator class="bg-orange-200/20" />

	<nav class="flex-1 space-y-1 px-3 py-4">
		{#each navItems as item}
			<a
				href={item.href}
				onclick={onClose}
				class={`block rounded-lg px-3 py-2 text-sm font-medium transition ${
					isActive(item.href) ? 'bg-orange-500 text-white' : 'text-orange-100 hover:bg-orange-100/15'
				}`}
			>
				{item.label}
			</a>
		{/each}
	</nav>

	<div class="p-3">
		<Button type="button" class="w-full" onclick={() => (showLogoutConfirm = true)}>
			Đăng xuất
		</Button>
	</div>
</aside>

<Sheet.Root open={open} onOpenChange={(nextOpen) => !nextOpen && onClose?.()}>
	<Sheet.Content side="left" class="w-[280px] bg-[#2f1e14] p-0 text-orange-50">
		<div class="px-5 py-4">
			<div class="flex items-center gap-3">
				<img src={LOGO_IMAGE} alt="Logo Tiệm Lẩu Anh Hai" loading="eager" decoding="async" class="size-9 rounded-md object-contain" />
				<div>
					<p class="text-xs uppercase tracking-wide text-orange-200/70">Tiệm Lẩu Anh Hai</p>
					<p class="mt-1 text-xl font-semibold">Admin Panel</p>
				</div>
			</div>
			<p class="mt-2 truncate text-sm text-orange-100/80">{adminEmail}</p>
		</div>
		<Separator class="bg-orange-200/20" />

		<nav class="flex-1 space-y-1 px-3 py-4">
			{#each navItems as item}
				<a
					href={item.href}
					onclick={onClose}
					class={`block rounded-lg px-3 py-2 text-sm font-medium transition ${
						isActive(item.href) ? 'bg-orange-500 text-white' : 'text-orange-100 hover:bg-orange-100/15'
					}`}
				>
					{item.label}
				</a>
			{/each}
		</nav>

		<div class="p-3">
			<Button type="button" class="w-full" onclick={() => (showLogoutConfirm = true)}>Đăng xuất</Button>
		</div>
	</Sheet.Content>
</Sheet.Root>

{#if showLogoutConfirm}
	<Dialog.Root open={showLogoutConfirm} onOpenChange={(nextOpen) => (showLogoutConfirm = nextOpen)}>
		<Dialog.Portal>
			<Dialog.Overlay />
			<Dialog.Content class="sm:max-w-sm">
				<Dialog.Header>
					<Dialog.Title>Xác nhận đăng xuất</Dialog.Title>
					<Dialog.Description>Bạn có chắc muốn đăng xuất khỏi trang quản trị không?</Dialog.Description>
				</Dialog.Header>
				<Dialog.Footer>
					<Button type="button" variant="outline" onclick={() => (showLogoutConfirm = false)}>Hủy</Button>
					<Button type="button" onclick={logout}>Đăng xuất</Button>
				</Dialog.Footer>
			</Dialog.Content>
		</Dialog.Portal>
	</Dialog.Root>
{/if}
