// src/components/admin/employee-form.tsx
'use client';

import { useEffect, useState } from 'react';
import {
  isStrongPassword,
  strongPasswordGuideline,
} from '@/lib/utils/password-policy';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';

type Employee = {
  id: string;
  email: string;
  role: 'super_admin' | 'manager';
  display_name?: string | null;
};

type RoleOption = {
  value: 'super_admin' | 'manager';
  label: string;
};

type Props = {
  open: boolean;
  mode: 'create' | 'edit';
  employee?: Employee | null;
  roleOptions: RoleOption[];
  onClose: () => void;
  onSaved?: () => void;
};

export function EmployeeForm({
  open,
  mode,
  employee,
  roleOptions,
  onClose,
  onSaved,
}: Props) {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [role, setRole] = useState<'super_admin' | 'manager'>('manager');
  const [displayName, setDisplayName] = useState('');
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');

  useEffect(() => {
    if (!open) return;
    setEmail(employee?.email ?? '');
    setPassword('');
    setRole(employee?.role ?? roleOptions[0]?.value ?? 'manager');
    setDisplayName(employee?.display_name ?? '');
    setMessage('');
  }, [open, employee, roleOptions]);

  async function save() {
    if (mode === 'create' && !isStrongPassword(password)) {
      setMessage(strongPasswordGuideline);
      return;
    }

    setSaving(true);
    setMessage('');

    const payload =
      mode === 'create'
        ? { email, password, role, displayName: displayName || null }
        : { role, displayName: displayName || null };
    const endpoint =
      mode === 'create'
        ? '/api/admin/employees'
        : `/api/admin/employees/${employee?.id}`;
    const method = mode === 'create' ? 'POST' : 'PATCH';

    try {
      const res = await fetch(endpoint, {
        method,
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(payload),
      });
      const data = await res.json();
      if (!res.ok) {
        setMessage(data.message ?? 'Không thể lưu nhân viên');
        return;
      }
      onSaved?.();
      onClose();
    } finally {
      setSaving(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={(next) => !next && onClose()}>
      <DialogContent className="max-w-xl">
        <DialogHeader>
          <DialogTitle>
            {mode === 'create' ? 'Thêm nhân viên' : 'Chỉnh sửa nhân viên'}
          </DialogTitle>
          <DialogDescription>
            {mode === 'create'
              ? 'Tạo tài khoản quản trị mới.'
              : 'Cập nhật vai trò hoặc tên hiển thị.'}
          </DialogDescription>
        </DialogHeader>

        <div className="mt-4 grid gap-3">
          <div className="grid gap-1">
            <Label>Email</Label>
            <Input
              type="email"
              value={email}
              disabled={mode === 'edit'}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="employee@example.com"
              className="disabled:bg-muted"
            />
          </div>

          {mode === 'create' ? (
            <div className="grid gap-1">
              <Label>Mật khẩu</Label>
              <Input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="Tối thiểu 8 ký tự"
              />
              <span className="text-xs text-muted-foreground">
                {strongPasswordGuideline}
              </span>
            </div>
          ) : null}

          <div className="grid gap-1">
            <Label>Tên hiển thị</Label>
            <Input
              type="text"
              value={displayName}
              onChange={(e) => setDisplayName(e.target.value)}
              placeholder="Ví dụ: Quản lý ca sáng"
            />
          </div>

          <div className="grid gap-1">
            <Label>Vai trò</Label>
            <Select
              value={role}
              onValueChange={(value) =>
                setRole(value as 'super_admin' | 'manager')
              }
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {roleOptions.map((option) => (
                  <SelectItem key={option.value} value={option.value}>
                    {option.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>

        {message ? (
          <p className="mt-4 rounded-md border border-destructive/50 bg-destructive/10 px-3 py-2 text-sm text-foreground">
            {message}
          </p>
        ) : null}

        <DialogFooter className="mt-4">
          <Button
            type="button"
            variant="outline"
            onClick={onClose}
            disabled={saving}
          >
            Hủy
          </Button>
          <Button type="button" onClick={save} disabled={saving}>
            {saving ? 'Đang lưu...' : 'Lưu'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// src/lib/components/admin/EmployeeForm.svelte
<script lang="ts">
	import { isStrongPassword, strongPasswordGuideline } from '$lib/utils/password-policy';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Dialog from '$lib/components/ui/dialog/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import { Label } from '$lib/components/ui/label/index.js';
	import * as Select from '$lib/components/ui/select/index.js';
	import { Alert, AlertDescription } from '$lib/components/ui/alert/index.js';

	type Employee = {
		id: string;
		email: string;
		role: 'super_admin' | 'manager';
		display_name?: string | null;
	};

	type RoleOption = {
		value: 'super_admin' | 'manager';
		label: string;
	};

	let {
		open,
		mode,
		employee = null,
		roleOptions = [],
		onClose,
		onSaved
	} = $props<{
		open: boolean;
		mode: 'create' | 'edit';
		employee?: Employee | null;
		roleOptions?: RoleOption[];
		onClose?: () => void;
		onSaved?: () => void;
	}>();

	let email = $state('');
	let password = $state('');
	let role = $state<'super_admin' | 'manager'>('manager');
	let displayName = $state('');
	let saving = $state(false);
	let message = $state('');

	$effect(() => {
		if (!open) return;
		email = employee?.email ?? '';
		password = '';
		role = employee?.role ?? (roleOptions[0]?.value ?? 'manager');
		displayName = employee?.display_name ?? '';
		message = '';
	});

	async function save() {
		saving = true;
		message = '';

		if (mode === 'create' && !isStrongPassword(password)) {
			saving = false;
			message = strongPasswordGuideline;
			return;
		}

		const payload =
			mode === 'create'
				? { email, password, role, displayName: displayName || null }
				: { role, displayName: displayName || null };

		const endpoint = mode === 'create' ? '/api/admin/employees' : `/api/admin/employees/${employee?.id}`;
		const method = mode === 'create' ? 'POST' : 'PATCH';

		const res = await fetch(endpoint, {
			method,
			headers: { 'content-type': 'application/json' },
			body: JSON.stringify(payload)
		});
		const data = await res.json();
		saving = false;

		if (!res.ok) {
			message = data.message ?? 'Không thể lưu nhân viên';
			return;
		}

		onSaved?.();
		onClose?.();
	}
</script>

<Dialog.Root open={open} onOpenChange={(nextOpen) => !nextOpen && onClose?.()}>
	<Dialog.Portal>
		<Dialog.Overlay />
		<Dialog.Content class="sm:max-w-xl">
			<Dialog.Header>
				<Dialog.Title>{mode === 'create' ? 'Thêm nhân viên' : 'Chỉnh sửa nhân viên'}</Dialog.Title>
				<Dialog.Description>
					{mode === 'create' ? 'Tạo tài khoản quản trị mới.' : 'Cập nhật vai trò hoặc tên hiển thị.'}
				</Dialog.Description>
			</Dialog.Header>

			<div class="grid gap-4 py-2">
				<div class="grid gap-2">
					<Label for="employee-email">Email</Label>
					<Input
						id="employee-email"
						type="email"
						bind:value={email}
						disabled={mode === 'edit'}
						placeholder="employee@example.com"
					/>
				</div>

				{#if mode === 'create'}
					<div class="grid gap-2">
						<Label for="employee-password">Mật khẩu</Label>
						<Input
							id="employee-password"
							type="password"
							bind:value={password}
							placeholder="Tối thiểu 8 ký tự"
						/>
						<p class="text-xs text-muted-foreground">{strongPasswordGuideline}</p>
					</div>
				{/if}

				<div class="grid gap-2">
					<Label for="employee-display-name">Tên hiển thị</Label>
					<Input
						id="employee-display-name"
						type="text"
						bind:value={displayName}
						placeholder="Ví dụ: Quản lý ca sáng"
					/>
				</div>

				<div class="grid gap-2">
					<Label for="employee-role">Vai trò</Label>
					<Select.Root type="single" bind:value={role}>
						<Select.Trigger id="employee-role" class="w-full">
							{#if role}
								{roleOptions.find((option: RoleOption) => option.value === role)?.label ?? role}
							{:else}
								Chọn vai trò
							{/if}
						</Select.Trigger>
						<Select.Content>
							{#each roleOptions as option}
								<Select.Item value={option.value} label={option.label}>{option.label}</Select.Item>
							{/each}
						</Select.Content>
					</Select.Root>
				</div>
			</div>

			{#if message}
				<Alert variant="destructive">
					<AlertDescription>{message}</AlertDescription>
				</Alert>
			{/if}

			<Dialog.Footer>
				<Button type="button" variant="outline" onclick={onClose} disabled={saving}>Hủy</Button>
				<Button type="button" onclick={save} disabled={saving}>
					{saving ? 'Đang lưu...' : 'Lưu'}
				</Button>
			</Dialog.Footer>
		</Dialog.Content>
	</Dialog.Portal>
</Dialog.Root>
