// src/lib/components/Header.svelte
<script lang="ts">
	import CartButton from '$lib/components/CartButton.svelte';
	import { LOGO_IMAGE } from '$lib/constants/assets';

	let { onOpenCart } = $props<{ onOpenCart?: () => void }>();
</script>

<header class="sticky top-0 z-40 border-b border-orange-200 bg-orange-50/90 backdrop-blur">
	<div class="container-shell flex h-16 items-center justify-between gap-4">
		<a href="/" class="flex items-center gap-3">
			<img src={LOGO_IMAGE} alt="Tiệm Lẩu Anh Hai" class="size-9 rounded-md object-contain" />
			<div>
				<p class="text-sm text-orange-800">Tiệm Lẩu</p>
				<p class="text-lg font-bold leading-none">Anh Hai</p>
			</div>
		</a>
		<nav class="hidden items-center gap-6 text-sm font-medium md:flex">
			<a href="/menu" class="hover:text-orange-700">Thực đơn</a>
			<a href="/orders" class="hover:text-orange-700">Đơn hàng</a>
		</nav>
		<CartButton onOpenCart={onOpenCart} />
	</div>
</header>

// src/components/Header.tsx
'use client';

import Link from 'next/link';
import { CartButton } from '@/components/CartButton';

export function Header() {
  return (
    <header className="sticky top-0 z-40 border-b border-border bg-background/90 backdrop-blur">
      <div className="container-shell flex h-16 items-center justify-between gap-4">
        <Link href="/" className="flex items-center gap-3">
          <img
            src="/logo.png"
            alt="Tiệm Lẩu Anh Hai"
            className="size-9 rounded-md object-contain"
          />
          <div>
            <p className="text-sm text-muted-foreground">Tiệm Lẩu</p>
            <p className="text-lg font-bold leading-none">Anh Hai</p>
          </div>
        </Link>
        <nav className="hidden items-center gap-6 text-sm font-medium md:flex">
          <Link href="/menu" className="hover:text-primary">
            Thực đơn
          </Link>
          <Link href="/orders" className="hover:text-primary">
            Đơn hàng
          </Link>
        </nav>
        <CartButton />
      </div>
    </header>
  );
}
