// src/lib/components/MenuItem.svelte
<script lang="ts">
	import { MENU_IMAGE } from '$lib/constants/assets';
	import { formatCurrency } from '$lib/utils/format';
	import type { MenuItem } from '$lib/types';
	import { Button } from '$lib/components/ui/button/index.js';
	import { Badge } from '$lib/components/ui/badge/index.js';
	import * as Card from '$lib/components/ui/card/index.js';

	let { item, onQuickAdd = () => {} } = $props<{
		item: MenuItem;
		onQuickAdd?: (item: MenuItem) => void;
	}>();

	const minPrice = $derived(Math.min(...item.variants.map((v: { price: number }) => v.price)));
	const maxPrice = $derived(Math.max(...item.variants.map((v: { price: number }) => v.price)));
</script>

<Card.Root class="flex h-full flex-col overflow-hidden">
	<a href={`/menu/${item.slug}`} class="block">
		<img
			src={item.thumbnail_url || MENU_IMAGE}
			alt={item.name}
			loading="lazy"
			decoding="async"
			class="h-36 w-full object-cover"
		/>
	</a>
	<div class="flex flex-1 flex-col px-3 py-2">
		<div class="flex items-start justify-between gap-3">
			<div>
				<h3 class="text-base font-semibold">{item.name}</h3>
				<p class="text-sm text-slate-600">{item.description ?? 'Món ngon chuẩn vị miền Tây'}</p>
			</div>
			{#if item.media.some((m: { type: string }) => m.type === 'video')}
				<Badge variant="secondary">Video</Badge>
			{/if}
		</div>
		<div class="mt-auto space-y-2.5 pt-4">
			<p class="font-semibold text-orange-700">
				{#if minPrice === maxPrice}
					{formatCurrency(minPrice)}
				{:else}
					{formatCurrency(minPrice)} - {formatCurrency(maxPrice)}
				{/if}
			</p>
			<div class="flex gap-2">
				<Button variant="outline" class="flex-1" href={`/menu/${item.slug}`}>Chi tiết</Button>
				<Button type="button" class="flex-1" onclick={() => onQuickAdd(item)}>Thêm vào giỏ</Button>
			</div>
		</div>
	</div>
</Card.Root>

// src/components/MenuItem.tsx
'use client';

import Link from 'next/link';
import type { MenuItem as MenuItemType } from '@/lib/types';
import { useCartStore } from '@/lib/stores/cart';
import { formatCurrency } from '@/lib/utils/format';
import { Button } from '@/components/ui/button';

type Props = {
  item: MenuItemType;
};

export function MenuItem({ item }: Props) {
  const add = useCartStore((state) => state.add);
  const minPrice = Math.min(...item.variants.map((variant) => variant.price));
  const maxPrice = Math.max(...item.variants.map((variant) => variant.price));

  const onQuickAdd = () => {
    const variant =
      item.variants.find((entry) => entry.is_default) ?? item.variants[0];
    if (!variant) return;
    add({
      variantId: variant.id,
      itemId: item.id,
      itemName: item.name,
      itemSlug: item.slug,
      variantName: variant.name,
      itemNote: item.note,
      price: variant.price,
      thumbnailUrl: item.thumbnail_url,
    });
  };

  return (
    <div className="card-surface flex h-full flex-col overflow-hidden">
      <Link href={`/menu/${item.slug}`} className="block">
        <img
          src={item.thumbnail_url || '/logo.png'}
          alt={item.name}
          className="h-36 w-full object-cover"
        />
      </Link>
      <div className="flex flex-1 flex-col px-3 py-2">
        <h3 className="text-base font-semibold">{item.name}</h3>
        <p className="text-sm text-muted-foreground">
          {item.description ?? 'Món ngon chuẩn vị miền Tây'}
        </p>
        <div className="mt-auto pt-4">
          <p className="font-semibold text-primary">
            {minPrice === maxPrice
              ? formatCurrency(minPrice)
              : `${formatCurrency(minPrice)} - ${formatCurrency(maxPrice)}`}
          </p>
          <div className="mt-2 flex gap-2">
            <Button asChild variant="outline" className="flex-1">
              <Link href={`/menu/${item.slug}`} className="text-center">
                Chi tiết
              </Link>
            </Button>
            <Button type="button" className="flex-1" onClick={onQuickAdd}>
              Thêm vào giỏ
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
