// src/app/admin/login/page.tsx
'use client';

import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

export default function AdminLoginPage() {
  const router = useRouter();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');

  async function login() {
    setLoading(true);
    setMessage('');
    try {
      const res = await fetch('/api/admin/auth/login', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ email, password }),
      });
      const data = await res.json();
      if (!res.ok) {
        setMessage(data.message ?? 'Không đăng nhập được');
        return;
      }
      router.push('/admin');
      router.refresh();
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="container-shell flex min-h-dvh items-center justify-center py-10">
      <div className="w-full max-w-md rounded-xl border border-border bg-card p-5 shadow-sm">
        <h1 className="text-2xl font-semibold">Admin Login</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Chỉ tài khoản admin hợp lệ mới truy cập được trang quản trị.
        </p>
        <div className="mt-4 grid gap-3">
          <div className="grid gap-1">
            <Label>Email</Label>
            <Input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="you@example.com"
            />
          </div>
          <div className="grid gap-1">
            <Label>Mật khẩu</Label>
            <Input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && !loading) login();
              }}
              placeholder="••••••••"
            />
          </div>
        </div>
        {message ? (
          <p className="mt-3 rounded-md border border-destructive/50 bg-destructive/10 px-3 py-2 text-sm text-foreground">
            {message}
          </p>
        ) : null}
        <Button
          type="button"
          onClick={login}
          disabled={loading}
          className="mt-4 w-full"
        >
          {loading ? 'Đang đăng nhập...' : 'Đăng nhập'}
        </Button>
      </div>
    </div>
  );
}

// src/routes/admin/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Card from '$lib/components/ui/card/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import { Label } from '$lib/components/ui/label/index.js';

let email = $state('');
	let password = $state('');
	let loading = $state(false);
	let message = $state('');

	async function login() {
		loading = true;
		message = '';

		const res = await fetch('/api/admin/auth/login', {
			method: 'POST',
			headers: { 'content-type': 'application/json' },
			body: JSON.stringify({ email, password })
		});

		const data = await res.json();
		loading = false;

		if (!res.ok) {
			message = data.message ?? 'Không đăng nhập được';
			return;
		}

		await goto('/admin');
	}
</script>

<main class="container-shell flex min-h-dvh items-center justify-center py-10">
	<Card.Root class="w-full max-w-md">
		<Card.Header>
			<Card.Title>Admin Login</Card.Title>
			<Card.Description>Chỉ tài khoản admin hợp lệ mới truy cập được trang quản trị.</Card.Description>
		</Card.Header>
		<Card.Content class="space-y-4">
			<div class="grid gap-2">
				<Label for="admin-email">Email</Label>
				<Input id="admin-email" type="email" bind:value={email} placeholder="you@example.com" />
			</div>
			<div class="grid gap-2">
				<Label for="admin-password">Mật khẩu</Label>
				<Input
					id="admin-password"
					type="password"
					bind:value={password}
					placeholder="••••••••"
					onkeydown={(event) => event.key === 'Enter' && !loading && login()}
				/>
			</div>
			{#if message}
				<p class="rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive">{message}</p>
			{/if}
		</Card.Content>
		<Card.Footer>
			<Button class="w-full" type="button" onclick={login} disabled={loading}>
				{loading ? 'Đang đăng nhập...' : 'Đăng nhập'}
			</Button>
		</Card.Footer>
	</Card.Root>
</main>
