// src/components/BottomNav.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useCartStore, selectCartCount } from '@/lib/stores/cart';

export function BottomNav() {
  const pathname = usePathname();
  const count = useCartStore(selectCartCount);

  return (
    <nav className="fixed inset-x-0 bottom-0 z-40 border-t border-border bg-background/95 md:hidden">
      <div className="mx-auto flex h-16 max-w-xl items-center justify-around">
        <Link
          href="/"
          className={`text-sm font-medium ${pathname === '/' ? 'text-primary' : 'text-muted-foreground'}`}
        >
          Trang chủ
        </Link>
        <Link
          href="/menu"
          className={`text-sm font-medium ${pathname.startsWith('/menu') ? 'text-primary' : 'text-muted-foreground'}`}
        >
          Menu
        </Link>
        <Link
          href="/cart"
          className={`relative text-sm font-medium ${pathname === '/cart' ? 'text-primary' : 'text-muted-foreground'}`}
        >
          Giỏ hàng
          {count > 0 ? (
            <span className="notification-badge-sm absolute -right-5 -top-3">
              {count}
            </span>
          ) : null}
        </Link>
        <Link
          href="/orders"
          className={`text-sm font-medium ${pathname.startsWith('/orders') ? 'text-primary' : 'text-muted-foreground'}`}
        >
          Đơn hàng
        </Link>
      </div>
    </nav>
  );
}

// src/lib/components/BottomNav.svelte
<script lang="ts">
	import { cartCount } from '$lib/stores/cart';
	import { page } from '$app/state';

	let current = $derived(page.url.pathname);

	function handleCartClick(event: MouseEvent) {
		if (current !== '/cart') return;
		event.preventDefault();
		window.scrollTo({ top: 0, behavior: 'smooth' });
	}
</script>

<nav class="fixed inset-x-0 bottom-0 z-40 border-t border-orange-200 bg-white/95 md:hidden">
	<div class="mx-auto flex h-16 max-w-xl items-center justify-around">
		<a href="/" class={`text-sm font-medium ${current === '/' ? 'text-orange-600' : 'text-slate-700'}`}>Trang chủ</a>
		<a href="/menu" class={`text-sm font-medium ${current.startsWith('/menu') ? 'text-orange-600' : 'text-slate-700'}`}>Menu</a>
		<a
			href="/cart"
			class={`relative text-sm font-medium ${current === '/cart' ? 'text-orange-600' : 'text-slate-700'}`}
			onclick={handleCartClick}
		>
			Giỏ hàng
			{#if $cartCount > 0}
				<span
					class="absolute -right-5 -top-3 inline-flex size-5 items-center justify-center rounded-full bg-orange-500 text-xs text-white"
				>
					{$cartCount}
				</span>
			{/if}
		</a>
		<a href="/orders" class={`text-sm font-medium ${current.startsWith('/orders') ? 'text-orange-600' : 'text-slate-700'}`}>
			Đơn hàng
		</a>
	</div>
</nav>
