// src/components/OrderConfirmModal.tsx
'use client';

import type { CartLine } from '@/lib/types';
import { formatCurrency } from '@/lib/utils/format';
import type { OrderFormModel } from '@/components/OrderForm';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';

type Props = {
  open: boolean;
  form: OrderFormModel;
  lines: CartLine[];
  totalAmount: number;
  scheduledDateLabel?: string;
  scheduledSlotLabel?: string;
  submitting?: boolean;
  onCancel: () => void;
  onConfirm: () => void;
};

export function OrderConfirmModal({
  open,
  form,
  lines,
  totalAmount,
  scheduledDateLabel,
  scheduledSlotLabel,
  submitting,
  onCancel,
  onConfirm,
}: Props) {
  const restaurantNotes = [
    ...new Set(lines.map((line) => line.itemNote?.trim()).filter(Boolean)),
  ];

  return (
    <Dialog
      open={open}
      onOpenChange={(next) => !next && !submitting && onCancel()}
    >
      <DialogContent
        className="max-h-[92vh] max-w-3xl overflow-y-auto rounded-2xl p-4 sm:p-5"
        onInteractOutside={(event) => {
          if (submitting) event.preventDefault();
        }}
        onEscapeKeyDown={(event) => {
          if (submitting) event.preventDefault();
        }}
        showCloseButton={!submitting}
      >
        <DialogHeader>
          <DialogTitle>Xác nhận thông tin đơn hàng</DialogTitle>
          <DialogDescription>
            Kiểm tra lại thông tin trước khi gửi đơn để quán xử lý nhanh hơn.
          </DialogDescription>
        </DialogHeader>
        <div className="mt-4 space-y-4 text-sm">
          <section className="rounded-xl border border-border bg-muted/40 p-3">
            <p className="font-medium">Thông tin khách hàng</p>
            <p className="mt-1">
              Họ tên: <strong>{form.customerName}</strong>
            </p>
            <p>
              SĐT: <strong>{form.phone}</strong>
            </p>
            <p>
              Địa chỉ:{' '}
              <strong>
                {form.address}, {form.ward}, {form.district}, {form.province}
              </strong>
            </p>
            <p>
              Ngày nhận món:{' '}
              <strong>{scheduledDateLabel || form.scheduledDate}</strong>
            </p>
            <p>
              Khung giờ nhận món:{' '}
              <strong>{scheduledSlotLabel || form.scheduledSlot}</strong>
            </p>
          </section>
          <section className="rounded-xl border border-border p-3">
            <p className="font-medium">Chi tiết đơn hàng</p>
            <div className="mt-2 space-y-2">
              {lines.map((line) => (
                <div
                  key={line.variantId}
                  className="flex items-start justify-between gap-3"
                >
                  <div>
                    <p>
                      {line.itemName} - {line.variantName}
                    </p>
                    <p className="text-xs text-muted-foreground">
                      {line.quantity} x {formatCurrency(line.price)}
                    </p>
                  </div>
                  <strong>{formatCurrency(line.price * line.quantity)}</strong>
                </div>
              ))}
            </div>
            <div className="mt-3 border-t border-border pt-2">
              <div className="flex items-center justify-between text-base">
                <span className="font-semibold">Tổng tiền món</span>
                <strong className="text-primary">
                  {formatCurrency(totalAmount)}
                </strong>
              </div>
            </div>
          </section>
          {form.note ? (
            <section className="rounded-xl border border-border p-3">
              <p className="font-medium">Ghi chú của khách</p>
              <p className="mt-1 text-muted-foreground">{form.note}</p>
            </section>
          ) : null}
          {restaurantNotes.length > 0 ? (
            <section className="rounded-xl border border-border bg-muted p-3">
              <p className="font-medium text-foreground">Lưu ý từ nhà hàng</p>
              <ul className="mt-1 list-disc space-y-1 pl-5 text-foreground">
                {restaurantNotes.map((note) => (
                  <li key={note}>{note}</li>
                ))}
              </ul>
            </section>
          ) : null}
        </div>
        <DialogFooter className="mt-5 border-t border-border pt-4 sm:justify-end">
          <Button
            variant="outline"
            type="button"
            onClick={onCancel}
            disabled={submitting}
          >
            Quay lại chỉnh sửa
          </Button>
          <Button type="button" onClick={onConfirm} disabled={submitting}>
            {submitting ? 'Đang tạo đơn...' : 'Đặt hàng'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// src/lib/components/OrderConfirmModal.svelte
<script lang="ts">
	import type { CartLine } from '$lib/types';
	import { formatCurrency } from '$lib/utils/format';

	let {
		form,
		lines = [] as CartLine[],
		totalAmount = 0,
		scheduledDateLabel = '',
		scheduledSlotLabel = '',
		submitting = false,
		onCancel = () => {},
		onConfirm = () => {}
	} = $props<{
		form: {
			customerName: string;
			phone: string;
			province: string;
			district: string;
			ward: string;
			address: string;
			note: string;
			scheduledDate: string;
			scheduledSlot: string;
		};
		lines: CartLine[];
		totalAmount: number;
		scheduledDateLabel?: string;
		scheduledSlotLabel?: string;
		submitting?: boolean;
		onCancel?: () => void;
		onConfirm?: () => void;
	}>();

	const restaurantNotes = $derived(
		Array.from(new Set(lines.map((line: CartLine) => line.itemNote?.trim()).filter(Boolean))) as string[]
	);
</script>

<div
	class="fixed inset-0 z-90 bg-black/40 p-3 sm:p-6"
	role="presentation"
	onclick={(event) => {
		if (event.target === event.currentTarget && !submitting) {
			onCancel();
		}
	}}
>
	<div class="mx-auto max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-background p-4 shadow-2xl sm:p-5">
		<div class="flex items-center justify-between gap-3 border-b border-orange-100 pb-3">
			<h2 class="text-xl font-semibold">Xác nhận thông tin đơn hàng</h2>
			<button class="btn-secondary" type="button" onclick={onCancel} disabled={submitting}>Đóng</button>
		</div>

		<div class="mt-4 space-y-4 text-sm">
			<section class="rounded-xl border border-orange-100 bg-orange-50/40 p-3">
				<p class="font-medium">Thông tin khách hàng</p>
				<p class="mt-1">Họ tên: <strong>{form.customerName}</strong></p>
				<p>SĐT: <strong>{form.phone}</strong></p>
				<p>
					Địa chỉ:
					<strong>{form.address}, {form.ward}, {form.district}, {form.province}</strong>
				</p>
				<p>
					Ngày nhận món:
					<strong>{scheduledDateLabel || form.scheduledDate}</strong>
				</p>
				<p>
					Khung giờ nhận món:
					<strong>{scheduledSlotLabel || form.scheduledSlot}</strong>
				</p>
			</section>

			<section class="rounded-xl border border-orange-100 p-3">
				<p class="font-medium">Chi tiết đơn hàng</p>
				<div class="mt-2 space-y-2">
					{#each lines as line}
						<div class="flex items-start justify-between gap-3">
							<div>
								<p>{line.itemName} - {line.variantName}</p>
								<p class="text-xs text-slate-500">
									{line.quantity} x {formatCurrency(line.price)}
								</p>
							</div>
							<strong>{formatCurrency(line.price * line.quantity)}</strong>
						</div>
					{/each}
				</div>
				<div class="mt-3 border-t border-orange-100 pt-2">
					<div class="flex items-center justify-between">
						<span>Tạm tính</span>
						<strong>{formatCurrency(totalAmount)}</strong>
					</div>
					<div class="mt-1 flex items-center justify-between text-base">
						<span class="font-semibold">Tổng tiền món</span>
						<strong class="text-orange-700">{formatCurrency(totalAmount)}</strong>
					</div>
				</div>
			</section>

			{#if form.note}
				<section class="rounded-xl border border-slate-200 p-3">
					<p class="font-medium">Ghi chú của khách</p>
					<p class="mt-1 text-slate-700">{form.note}</p>
				</section>
			{/if}

			{#if restaurantNotes.length > 0}
				<section class="rounded-xl border border-amber-300 bg-amber-50 p-3">
					<p class="font-medium text-amber-900">Lưu ý từ nhà hàng</p>
					<ul class="mt-1 list-disc space-y-1 pl-5 text-amber-900">
						{#each restaurantNotes as note}
							<li>{note}</li>
						{/each}
					</ul>
				</section>
			{/if}

			<section class="rounded-xl border border-blue-200 bg-blue-50 p-3 text-blue-950">
				<p class="font-medium">Lưu ý vận chuyển</p>
				<p class="mt-1">Giá món ăn chưa bao gồm phí vận chuyển.</p>
				<p class="mt-1">Sau khi xác nhận đơn, nhà hàng sẽ kiểm tra mức phí với đơn vị vận chuyển.</p>
				<p class="mt-1">Nhà hàng sẽ thông tin lại để mình thanh toán phí vận chuyển giúp đơn được giao nhanh nhất ạ.</p>
			</section>
		</div>

		<div class="mt-5 flex flex-col gap-2 border-t border-orange-100 pt-4 sm:flex-row sm:justify-end">
			<button class="btn-secondary" type="button" onclick={onCancel} disabled={submitting}>
				Quay lại chỉnh sửa
			</button>
			<button class="btn-primary" type="button" onclick={onConfirm} disabled={submitting}>
				{submitting ? 'Đang tạo đơn...' : 'Đặt hàng'}
			</button>
		</div>
	</div>
</div>
